local battle_map_conf = {
[1] ={
	id = 1,
	bg_ccb = 'RABattleMap_RTS_1_1.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
    plot_ccb= 'RABattleMap_RTS_1_1_Plot.ccbi', 
	tmx = 'RABattleMap_Block_RTS_1_1.tmx',
	init_scale = 0.9, 					-- 镜头初始化缩放值
	min_scale = 0.5,					-- 最大最小值
	max_scale = 1.6,
	bounce_min_scale = 0.7,				-- 回弹最大最小值
	bounce_max_scale = 1.5,
    camera_init_grid_pos = '36_64',	-- 初始化镜头的格子
	original_width = 1707,
	original_height = 2045,
	prepareMusic = 10027,
	fightMusic = 10027,
},
[2] ={
	id = 2,
	bg_ccb = 'RABattleMap_RTS_1_2.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
	tmx = 'RABattleMap_Block_RTS_1_2.tmx',
	min_scale = 0.9,
	init_scale = 0.8, -- Ä¬ÈÏ0.9
	max_scale = 1.7,
	bounce_min_scale = 0.68,		-- 回弹
	bounce_max_scale = 1.66,
	camera_init_grid_pos = '109_104',	-- 初始化镜头的格子
	original_width = 2126,
	original_height = 1952,
	prepareMusic = 10027,
	fightMusic = 10027,
},
[3] ={
	id = 3,
	bg_ccb = 'RABattleMap_RTS_1_3.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
	tmx = 'RABattleMap_Block_RTS_1_3.tmx',
	min_scale = 0.9,
	init_scale = 0.8, -- Ä¬ÈÏ0.9
	max_scale = 1.5,
	bounce_min_scale = 0.68,		-- 回弹
	bounce_max_scale = 1.45,
	camera_init_grid_pos = '140_80',	-- 初始化镜头的格子
	original_width = 2919,
	original_height = 1701,
	prepareMusic = 10027,
	fightMusic = 10027,
},
[4] ={
	id = 4,
	bg_ccb = 'RABattleMap_RTS_1_4.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
    plot_ccb= 'RABattleMap_RTS_1_4_plot.ccbi', 
	tmx = 'RABattleMap_Block_RTS_1_4.tmx',
	min_scale = 0.9,
	init_scale = 0.8, -- Ä¬ÈÏ0.9
	max_scale = 1.7,
	bounce_min_scale = 0.68,		-- 回弹
	bounce_max_scale = 1.66,
	camera_init_grid_pos = '10_45',	-- 初始化镜头的格子
	original_width = 2048,
	original_height = 2048,
	prepareMusic = 10026,
	fightMusic = 10026,
},
[5] ={
	id = 5,
	bg_ccb = 'RABattleMap_RTS_1_5.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
	tmx = 'RABattleMap_Block_RTS_1_5.tmx',
	min_scale = 0.9,
	init_scale = 0.8, -- Ä¬ÈÏ0.9
	max_scale = 1.7,
	bounce_min_scale = 0.68,		-- 回弹
	bounce_max_scale = 1.66,
	camera_init_grid_pos = '61_93',	-- 初始化镜头的格子
	original_width = 2624,
	original_height = 1900,
	prepareMusic = 10026,
	fightMusic = 10026,
},
[6] ={
	id = 6,
	bg_ccb = 'RABattleMap_RTS_1_6.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
	tmx = 'RABattleMap_Block_RTS_1_6.tmx',
	min_scale = 0.9,
	init_scale = 0.8, -- Ä¬ÈÏ0.9
	max_scale = 1.7,
	bounce_min_scale = 0.68,		-- 回弹
	bounce_max_scale = 1.66,
	camera_init_grid_pos = '130_76',	-- 初始化镜头的格子
	original_width = 2140,
	original_height = 1772,
	prepareMusic = 10028,
	fightMusic = 10028,
},
[7] ={
	id = 7,
	bg_ccb = 'RABattleMap_RTS_1_7.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
	tmx = 'RABattleMap_Block_RTS_1_7.tmx',
	min_scale = 0.9,
	init_scale = 0.8, -- Ä¬ÈÏ0.9
	max_scale = 1.7,
	bounce_min_scale = 0.68,		-- 回弹
	bounce_max_scale = 1.66,
	camera_init_grid_pos = '67_89',	-- 初始化镜头的格子
	original_width = 1181,    
	original_height = 1457,
	prepareMusic = 10028,
	fightMusic = 10028,
},
[8] ={
	id = 8,
	bg_ccb = 'RABattleMap_RTS_1_8.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
	tmx = 'RABattleMap_Block_RTS_1_8.tmx',
	min_scale = 0.9,
	init_scale = 0.8, -- Ä¬ÈÏ0.9
	max_scale = 1.7,
	bounce_min_scale = 0.68,		-- 回弹
	bounce_max_scale = 1.66,
	camera_init_grid_pos = '114_52',	-- 初始化镜头的格子
	original_width = 2413,
	original_height = 1435,
	prepareMusic = 10028,
	fightMusic = 10028,
},
[101] ={
	id = 101,
	bg_ccb = 'RABattleMap_Grass_2.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
	tmx = 'RABattleMap_Block_Grass_2.tmx',
	min_scale = 0.5,
	init_scale = 0.9,
	max_scale = 3,
	original_width = 1900,
	original_height = 1425,
	prepareMusic = 10018,
	fightMusic = 10018,
},
[102] ={
	id = 102,
	bg_ccb = 'RABattleMap_Grass_3.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
	tmx = 'RABattleMap_Block_Grass_3.tmx',
	min_scale = 0.5,
	init_scale = 0.9,
	max_scale = 3,
	original_width = 1900,
	original_height = 1350,
	prepareMusic = 10018,
	fightMusic = 10018,
},
[90001] = { -- devtest 程序开发测试专用，不要删除
	id = 90001,
	bg_ccb = 'RABattleMap_RTS_1.ccbi',
	weather_ccb= 'RABattleMap_Grass_Weather.ccbi', 
	tmx = 'RABattleMap_Block_RTS_1.tmx',
	min_scale = 0.5,
	init_scale = 1.1, -- Ä¬ÈÏ0.9
	max_scale = 3,
	bounce_min_scale = 0.7,		-- 回弹
	bounce_max_scale = 2.8,
	camera_init_grid_pos = '141_132',	-- 初始化镜头的格子
	original_width = 2413,
	original_height = 1435,
	prepareMusic = 10018,
	fightMusic = 10018,
}
}
return battle_map_conf
