local mainUI_status_btn_conf = {
[1] ={
	id = 1,
	iconBg = 'V3MainUI_Btn_InCome.png',
	line = 3,
	width = 75,
},
[2] ={
	id = 2,
	iconBg = 'V3MainUI_Btn_Buff.png',
	line = 3,
	width = 75,
},
[3] ={
	id = 3,
	iconBg = 'V3MainUI_Btn_Btm_02.png',
	line = 2,
	width = 75,
	icon = 'V3MainUI_Btn_03_C1.png',
	iconFx = 'V3MainUI_Btn_03_C1.png',
},
[4] ={
	id = 4,
	iconBg = 'V3MainUI_Btn_Btm_02.png',
	line = 2,
	width = 75,
	icon = 'V3MainUI_Btn_03_C3.png',
	iconFx = 'V3MainUI_Btn_03_C3.png',
},
[5] ={
	id = 5,
	iconBg = 'V3MainUI_Btn_Btm_02.png',
	line = 2,
	width = 75,
	icon = 'V3MainUI_Btn_03_C4.png',
	iconFx = 'V3MainUI_Btn_03_C4.png',
},
[6] ={
	id = 6,
	iconBg = 'V3MainUI_Btn_Btm_01.png',
	line = 3,
	width = 75,
	icon = 'V3MainUI_Btn_03_C5.png',
	iconFx = 'V3MainUI_Btn_03_C5.png',
},
[7] ={
	id = 7,
	iconBg = 'V3MainUI_Btn_Btm_02.png',
	line = 2,
	width = 75,
	icon = 'V3MainUI_Btn_03_C2.png',
	iconFx = 'V3MainUI_Btn_03_C2.png',
},
[8] ={
	id = 8,
	iconBg = 'V3MainUI_Btn_Btm_02.png',
	line = 1,
	width = 75,
	icon = 'V3MainUI_Btn_03_C2.png',
	iconFx = 'V3MainUI_Btn_03_C2.png',
},
[9] ={
	id = 9,
	iconBg = 'V3MainUI_Btn_Btm_02_C.png',
	line = 1,
	width = 75,
	icon = 'V3MainUI_Btn_03_C12.png',
	iconFx = 'V3MainUI_Btn_03_C12.png',
	name = '2,@NS_EntranceState1;3,@NS_EntranceState2;4,@NS_EntranceState3;5,@NS_EntranceState3',
},
[10] ={
	id = 10,
	iconBg = 'V3MainUI_Btn_Btm_01.png',
	line = 1,
	width = 75,
	icon = 'V3MainUI_Btn_03_C8.png',
},
[11] ={
	id = 11,
	iconBg = 'V3MainUI_Btn_Btm_02_B.png',
	line = 1,
	width = 75,
	icon = 'V3MainUI_Btn_03_C9.png',
	name = '@AF_BuffTipsName',
},
[12] ={
	id = 12,
	iconBg = 'V3MainUI_Btn_Btm_02.png',
	line = 1,
	width = 75,
	icon = 'V5Activity_164_World_u_HUD_Search.png',
	name = '@Act164SnowBall',
},
[13] ={
	id = 13,
	iconBg = 'V3MainUI_Btn_Btm_02.png',
	line = 2,
	width = 75,
	icon = 'V3MainUI_Btn_03_C2.png',
	iconFx = 'V3MainUI_Btn_03_C2.png',
},
[14] ={
	id = 14,
	iconBg = 'V3MainUI_Btn_Btm_02_B.png',
	line = 3,
	width = 75,
	icon = 'V3MainUI_Btn_03_C10.png',
	name = '@SWBuff',
},
[15] ={
	id = 15,
	iconBg = 'V3MainUI_Btn_Btm_02_C.png',
	line = 3,
	width = 75,
	icon = 'V3MainUI_Btn_03_C11.png',
},
[19] ={
	id = 19,
	iconBg = 'V3MainUI_Btn_Btm_02_C.png',
	line = 1,
	width = 75,
	icon = 'V3MainUI_Btn_03_C11.png',
}
}
return mainUI_status_btn_conf
