local page_tabs_conf = {
['RAPackageUIPage'] ={
	name = 'RAPackageUIPage',
	itemAmount = 5,
	icon1 = 'V3CommonUI_Icon_Tab_All',
	title1 = '@ItemInterphaseTab_All',
	icon2 = 'V3CommonUI_Icon_Tab_Res',
	title2 = '@ItemInterphaseTab_Res',
	icon3 = 'V3CommonUI_Icon_Tab_SpeedUp',
	title3 = '@ItemInterphaseTab_SpeedUp',
	icon4 = 'V3CommonUI_Icon_Tab_Buff',
	title4 = '@ItemInterphaseTab_Buff',
	icon5 = 'V3CommonUI_Icon_Tab_Other',
	title5 = '@ItemInterphaseTab_Other',
},
['RAReposityPage'] ={
	name = 'RAReposityPage',
	itemAmount = 4,
	icon1 = 'V3CommonUI_Icon_Tab_Stone',
	title1 = '@ResName1007',
	icon2 = 'V3CommonUI_Icon_Tab_Oil',
	title2 = '@ResName1008',
	icon3 = 'V3CommonUI_Icon_Tab_Gold',
	title3 = '@ResName1010',
	icon4 = 'V3CommonUI_Icon_Tab_Soil',
	title4 = '@ResName1009',
},
['RAChatUIPage'] ={
	name = 'RAChatUIPage',
	itemAmount = 3,
	icon1 = 'V4Chat_World',
	title1 = '@World',
	icon2 = 'V4Chat_Alliance',
	title2 = '@AllianceWithTwoBlanks',
	icon3 = 'V6CommonUI_Icon_Tab_Helper',
	title3 = '@Chat_Page_Tab4',
},
['RAActivityMergeCompleteRewardPopUp'] ={
	name = 'RAActivityMergeCompleteRewardPopUp',
	itemAmount = 3,
	title1 = '@RAAct368Lang12',
	title2 = '@RAAct368Lang13',
	title3 = '@RAAct368Lang14',
},
['RAActivityMergeCompleteMainPage'] ={
	name = 'RAActivityMergeCompleteMainPage',
	itemAmount = 3,
	tabCCBName = 'mCommonPopUpCCB3',
	title1 = '@RAAct368Lang1',
	title2 = '@RAAct368Lang2',
	title3 = '@RAAct368Lang3',
},
['RARadarReportListPage'] ={
	name = 'RARadarReportListPage',
	itemAmount = 2,
	tabCCBName = 'mCommonTab2CCB',
	title1 = '@IntelligenceBtn1',
	title2 = '@IntelligenceBtn2',
},
['RAChatUIPage_Anchor'] ={
	name = 'RAChatUIPage_Anchor',
	itemAmount = 4,
	icon1 = 'V4Chat_World',
	title1 = '@World',
	icon2 = 'V4Chat_Alliance',
	title2 = '@AllianceWithTwoBlanks',
	icon3 = 'V4Chat_Anchor',
	title3 = '@Anchor',
	icon4 = 'V6CommonUI_Icon_Tab_Helper',
	title4 = '@Chat_Page_Tab4',
},
['RAChatAnchorRankPage'] ={
	name = 'RAChatAnchorRankPage',
	itemAmount = 3,
	icon1 = 'V5CommonUI_Icon_Tab_Today',
	title1 = '@Today',
	icon2 = 'V5CommonUI_Icon_Tab_Week',
	title2 = '@AnchorWeekRank',
	icon3 = 'V5CommonUI_Icon_Tab_All',
	title3 = '@AnchorTotalRank',
},
['RASettingPage'] ={
	name = 'RASettingPage',
	tabCCBName = 'RAzzPageCommonTab3V3.ccbi',
	itemAmount = 3,
	icon1 = 'V3CommonUI_Icon_Tab_Option',
	title1 = '@ResNameOptions',
	icon2 = 'V3CommonUI_Icon_Tab_Push',
	title2 = '@ResNamePush',
	icon3 = 'V5CommonUI_Tab_ActRemind',
	title3 = '@Push_Activity',
},
['RATaskPage'] ={
	name = 'RATaskPage',
	itemAmount = 2,
	title1 = '@DailyTask',
	title2 = '@GeneralTask',
},
['RATBLYSkillSysMainPage'] ={
	name = 'RATBLYSkillSysMainPage',
	itemAmount = 2,
	title1 = '@TBLYBuildingSkillTab',
	title2 = '@TBLYOrderTab',
},
['RAWorldYQZZBattleMgrPopUp'] ={
	name = 'RAWorldYQZZBattleMgrPopUp',
	itemAmount = 2,
	title1 = '@RAWorldYQZZBattleMgrTab1',
	title2 = '@RAWorldYQZZBattleMgrTab2',
},

['RAActivityMergeCompleteRewardRankPopUpAlliance'] ={
	name = 'RAActivityMergeCompleteRewardRankPopUpAlliance',
	itemAmount = 2,
	title1 = '@RAAct368Lang20',
	title2 = '@RAAct368Lang14',
},
['RAActivityMergeCompleteRewardRankPopUpPlayer'] ={
	name = 'RAActivityMergeCompleteRewardRankPopUpPlayer',
	itemAmount = 2,
	title1 = '@RAAct368Lang21',
	title2 = '@RAAct368Lang14',
},
['RAHeroListPage'] ={
	name = 'RAHeroListPage',
	itemAmount = 5,
	icon1 = 'V3CommonUI_Icon_Tab_All',
	title1 = '@TabBtn1',
	icon2 = 'V3CommonUI_Icon_Tab_Military',
	title2 = '@TabBtn2',
	icon3 = 'V3CommonUI_Icon_Tab_Resources',
	title3 = '@TabBtn3',
	icon4 = 'V3CommonUI_Icon_Tab_Train',
	title4 = '@TabBtn4',
	icon5 = 'V3CommonUI_Icon_Tab_HeroAppoint',
	title5 = '@attrName1011',
},
['RAAceCommanderPage'] ={
	name = 'RAAceCommanderPage',
	itemAmount = 3,
	title1 = '@BlackListTab1',
	title2 = '@BlackListTab2',
	title3 = '@BlackListTab3',
},
['RAAceCommanderRankPopUp'] ={
	name = 'RAAceCommanderRankPopUp',
	itemAmount = 2,
	title1 = '@Act162_AllRankTitle',
	title2 = '@Act162_StageRankTitle',
},

['RANewAceCommanderPage'] ={
	name = 'RANewAceCommanderPage',
	itemAmount = 3,
	title1 = '@BlackListTab1',
	title2 = '@BlackListTab2',
	title3 = '@BlackListTab3',
},
['RANewAceCommanderRankPopUp'] ={
	name = 'RANewAceCommanderRankPopUp',
	itemAmount = 2,
	title1 = '@Act162_AllRankTitle',
	title2 = '@Act162_StageRankTitle',
},
['RAHeroMainPage'] ={
	name = 'RAHeroMainPage',
	itemAmount = 4,
	icon1 = 'V3CommonUI_Icon_Tab_Synopsis',
	title1 = '@TabBtnLabel1',
	icon2 = 'V3CommonUI_Icon_Tab_Upgrade',
	title2 = '@TabBtnLabel2',
	icon3 = 'V3CommonUI_Icon_Tab_PromoteStar',
	title3 = '@TabBtnLabel3',
	icon4 = 'V3CommonUI_Icon_Tab_HeroSkill',
	title4 = '@TabBtnLabel4',
},
['RAHeroMainPage2'] ={
	name = 'RAHeroMainPage2',
	itemAmount = 4,
	icon1 = 'V3CommonUI_Icon_Tab_Synopsis',
	title1 = '@TabBtnLabel1',
	icon2 = 'V3CommonUI_Icon_Tab_Upgrade',
	title2 = '@TabBtnLabel2',
	icon3 = 'V3CommonUI_Icon_Tab_HeroTalent',
	title3 = '@TabBtnLabel5',
	icon4 = 'V3CommonUI_Icon_Tab_HeroSkill',
	title4 = '@TabBtnLabel4',
},
['RAHeroMainPage3'] ={
	name = 'RAHeroMainPage3',
	itemAmount = 4,
	icon1 = 'V3CommonUI_Icon_Tab_Synopsis',
	title1 = '@TabBtnLabel1',
	icon2 = 'V3CommonUI_Icon_Tab_Upgrade',
	title2 = '@TabBtnLabel2',
	icon3 = 'V3CommonUI_Icon_Tab_HeroTalent',
	title3 = '@RAHeroSoulLang1',
	icon4 = 'V3CommonUI_Icon_Tab_HeroSkill',
	title4 = '@TabBtnLabel4',
},
['RAMobaWarHeroMainPage'] ={
	name = 'RAMobaWarHeroMainPage',
	itemAmount = 4,
	icon1 = 'V3CommonUI_Icon_Tab_Synopsis',
	title1 = '@TabBtnLabel1',
	icon2 = 'V3CommonUI_Icon_Tab_Upgrade',
	title2 = '@TabBtnLabel2',
	icon3 = 'V3CommonUI_Icon_Tab_PromoteStar',
	title3 = '@TabBtnLabel3',
	icon4 = 'V3CommonUI_Icon_Tab_HeroSkill',
	title4 = '@TabBtnLabel4',
},
['RARankDetailsPage'] ={
	name = 'RARankDetailsPage',
	itemAmount = 5,
	title1 = '@RankCommanderFightValue',
	title2 = '@RankCommanderEnemyDefeat',
	title3 = '@RankCommanderBase',
	title4 = '@RankCommanderLevel',
	title5 = '@MigrantLang50',
},
['RARankDetailsAlliancePage'] ={
	name = 'RARankDetailsAlliancePage',
	itemAmount = 2,
	title1 = '@RankAllianceFightValue',
	title2 = '@RankAllianceEnemyDefeat',
},
['RAWorldFavoritesPage'] ={
	name = 'RAWorldFavoritesPage',
	itemAmount = 5,
	icon1 = 'V3CommonUI_Icon_Tab_All',
	title1 = '@All',
	icon2 = 'V3CommonUI_Icon_Tab_Alliance',
	title2 = '@AllianceBase',
	icon3 = 'V3CommonUI_Icon_Tab_Sign',
	title3 = '@Target',
	icon4 = 'V3CommonUI_Icon_Tab_Friend',
	title4 = '@Friends',
	icon5 = 'V3CommonUI_Icon_Tab_Enemy',
	title5 = '@Enemy',
},
['RAGachaMainPage'] ={
	name = 'RAGachaMainPage',
	itemAmount = 2,
	icon1 = 'V3CommonUI_Icon_Tab_HeroGacha',
	title1 = '@PandectOtherHero',
	icon2 = 'V3CommonUI_Icon_Tab_HeroSkill',
	title2 = '@skillResearch',
},
['RATroopsInfoPage'] ={
	name = 'RATroopsInfoPage',
	itemAmount = 3,
	icon1 = 'V3CommonUI_Icon_Tab_CityTroops',
	title1 = '@CityArmys',
	icon2 = 'V3CommonUI_Icon_Tab_BattleTroops',
	title2 = '@OutArmys',
	icon3 = 'V3CommonUI_Icon_Tab_Shelter',
	title3 = '@Shelter',
},

['RAHeroSkillListPopUp'] ={
	name = 'RAHeroSkillListPopUp',
	itemAmount = 3,
	title1 = '@TabBtn2',
	title2 = '@TabBtn3',
	title3 = '@TabBtn4',
},
['RAGachaPreviewPopUp'] ={
	name = 'RAGachaPreviewPopUp',
	itemAmount = 2,
	title1 = '@normalHeroPoolPreview',
	title2 = '@highHeroPoolPreview',
},
['RAGachaPreviewPopUp_Skill'] ={
	name = 'RAGachaPreviewPopUp_Skill',
	itemAmount = 3,
	title1 = '@skillPoolPreview_Military',
	title2 = '@skillPoolPreview_Resources',
	title3 = '@skillPoolPreview_Train',
},
['RAMechaCoreEffectPopUp'] ={
	name = 'RAMechaCoreEffectPopUp',
	itemAmount = 3,
	title1 = '@RAMechaCoreLang73',
	title2 = '@RAMechaCoreLang74',
	title3 = '@RAMechaCoreLang75',
},
['RAMechaCoreGachaPreviewPopUp'] ={
	name = 'RAMechaCoreGachaPreviewPopUp',
	cellCCBName = 'RATroopChargeQUTabNodeV3.ccbi',
	itemAmount = 5,
	title1 = '@RAMechaCoreLang83',
	title2 = '@RAMechaCoreLang82',
	title3 = '@RAMechaCoreLang81',
	title4 = '@RAMechaCoreLang80',
	title5 = '@RAMechaCoreLang79',
},
['RAAllianceTreasurePage'] ={
	name = 'RAAllianceTreasurePage',
	itemAmount = 3,
	icon1 = 'V3CommonUI_Icon_Tab_ALTreasure_01',
	title1 = '@AllianceTreasure_List',
	icon2 = 'V3CommonUI_Icon_Tab_ALTreasure_02',
	title2 = '@AllianceTreasure_MyList',
	icon3 = 'V3CommonUI_Icon_Tab_ALTreasure_03',
	title3 = '@AllianceTreasure_HelpList',
},
['RAWXFriendsPage'] ={
	name = 'RAWXFriendsPage',
	itemAmount = 3,
	icon1 = 'V3CommonUI_Icon_Tab_WeChat',
	title1 = '@WXFriend',
	icon2 = 'V3CommonUI_Icon_Tab_Friends',
	title2 = '@GameFriend',
	icon3 = 'V3CommonUI_Icon_Tab_Search',
	title3 = '@searchAndAdd',
},
['RAQQFriendsPage'] ={
	name = 'RAQQFriendsPage',
	itemAmount = 3,
	icon1 = 'V3CommonUI_Icon_Tab_QQ',
	title1 = '@QQFriend',
	icon2 = 'V3CommonUI_Icon_Tab_Friends',
	title2 = '@GameFriend',
	icon3 = 'V3CommonUI_Icon_Tab_Search',
	title3 = '@searchAndAdd',
},
['RAGuestFriendsPage'] ={
	name = 'RAGuestFriendsPage',
	itemAmount = 2,
	icon1 = 'V3CommonUI_Icon_Tab_Friends',
	title1 = '@GameFriend',
	icon2 = 'V3CommonUI_Icon_Tab_Search',
	title2 = '@searchAndAdd',
},
['RASuperBarracksDetailPage'] ={
	name = 'RASuperBarracksDetailPage',
	itemAmount = 4,
	icon1 = 'V3CommonUI_Icon_Tab_Reward',
	title1 = '@SuperBarrackDetailAward',
	icon2 = 'V3CommonUI_Icon_Tab_Reward',
	title2 = '@SuperBarrackSectionAward',
	icon3 = 'V3CommonUI_Icon_Tab_Rule',
	title3 = '@SuperBarrackSectionDetail',
	icon4 = 'V3CommonUI_Icon_Tab_Rule',
	title4 = '@SuperBarrackDetailRules',
},
['RAMailChatSelectMemsPage'] ={
	name = 'RAMailChatSelectMemsPage',
	itemAmount = 3,
	title1 = '@HistoryInteraction',
	title2 = '@Alliance',
	title3 = '@Friends',
},
['RAResourceHubDetailTypePopUp'] ={
	name = 'RAResourceHubDetailTypePopUp',
	itemAmount = 2,
	icon1 = 'V3CommonUI_Icon_Tab_AddDetails',
	title1 = '@AddDetails',
	icon2 = 'V3CommonUI_Icon_Tab_ResDetails',
	title2 = '@ResDetails',
},
['RAAvatarMainPage'] ={
	name = 'RAAvatarMainPage',
	itemAmount = 2,
	icon1 = 'V3CommonUI_Icon_Tab_ChangeFrame',
	title1 = '@PlayerPortraitFrameBar',
	icon2 = 'V3CommonUI_Icon_Tab_ChangePortrait',
	title2 = '@PlayerPortraitBar',
},
['RAHeroAppointPage'] ={
	name = 'RAHeroAppointPage',
	itemAmount = 3,
	icon1 = 'V3CommonUI_Icon_Tab_Military',
	title1 = '@MilitaryAdjutant',
	icon2 = 'V3CommonUI_Icon_Tab_Resources',
	title2 = '@DevelopingAdjutant',
	icon3 = 'V3CommonUI_Icon_Tab_Train',
	title3 = '@AuxiliaryAdjutant',
},
['RAFriendsInvitePage'] ={
	name = 'RAFriendsInvitePage',
	itemAmount = 2,
	icon1 = 'V3CommonUI_Icon_Tab_ChangeFrame',
	title1 = '@PeopleNumberReward',
	icon2 = 'V3CommonUI_Icon_Tab_ChangePortrait',
	title2 = '@CityLevelReward',
},
['RAFriendsInviteListPage'] ={
	name = 'RAFriendsInviteListPage',
	itemAmount = 2,
	icon1 = 'V3CommonUI_Icon_Tab_AddDetails',
	title1 = '@FriendsFamiliarity',
	icon2 = 'V3CommonUI_Icon_Tab_ResDetails',
	title2 = '@FriendsAlreadyInvited',
},
['RAActivityStrongCommanderRankAndReward'] ={
	name = 'RAActivityStrongCommanderRankAndReward',
	itemAmount = 2,
	icon1 = 'V3CommonUI_Icon_Tab_ChangeFrame',
	title1 = '@PhaseRank',
	icon2 = 'V3CommonUI_Icon_Tab_ChangePortrait',
	title2 = '@TotalRank',
},
['RAAchievementPage'] ={
	name = 'RAAchievementPage',
	itemAmount = 5,
	title1 = '@AchievementTitleNote1',
	title2 = '@AchievementTitleNote2',
	title3 = '@AchievementTitleNote3',
	title4 = '@AchievementTitleNote4',
	title5 = '@AchievementTitleNote5',
},
['RAPubDailyPage'] ={
	name = 'RAPubDailyPage',
	itemAmount = 4,
	icon1 = 'V5Quest_Btn_World',
	title1 = '@DailyTaskTypeTitle1',
	icon2 = 'V5Quest_Btn_Sociality',
	title2 = '@DailyTaskTypeTitle2',
	icon3 = 'V5Quest_Btn_Buuild',
	title3 = '@DailyTaskTypeTitle3',
	icon4 = 'V5Quest_Btn_Military',
	title4 = '@DailyTaskTypeTitle4',
},
['RAAllianceApplicationPage'] ={
	name = 'RAAllianceApplicationPage',
	itemAmount = 2,
	icon1 = 'V5CommonUI_Icon_Tab_Apply',
	title1 = '@ApplicationTitle1',
	icon2 = 'V5CommonUI_Icon_Tab_Invite',
	title2 = '@ApplicationTitle2',
},
['RARechargeMainPage'] ={
	name = 'RARechargeMainPage',
	itemAmount = 3,
	title1 = '@StoreTabTitle1',
	title2 = '@DiamondShop',
	title3 = '@StoreTabTitle4',
},
['RAGiftMainPage'] ={
	name = 'RAGiftMainPage',
	itemAmount = 3,
	title1 = '@StoreTabTitle2',
	title2 = '@StoreTabTitle3',
	title3 = '@WeeklyCard',
},
['RATaskMainPage'] ={
	name = 'RATaskMainPage',
	itemAmount = 3,
	title1 = '@TaskScheduleTitle',
	title2 = '@itemGetTitle5',
	title3 = '@itemGetTitle4',
},
['RAWorldWarAppointmentPage'] ={
	name = 'RAWorldWarAppointmentPage',
	itemAmount = 2,
	icon1 = 'V5CommonUI_Tab_WarMem',
	title1 = '@AllianceMem',
	icon2 = 'V5CommonUI_Tab_WarSearch',
	title2 = '@Player',
},
['RACycleRankPopUp'] ={
	name = 'RACycleRankPopUp',
	itemAmount = 2,
	icon1 = 'V5CommonUI_Tab_WarMem',
	title1 = '@ActivityHellfireRankMessageTitle',
	icon2 = 'V5CommonUI_Tab_WarSearch',
	title2 = '@ActivityHellfireRankRewardTitle',
},
['RAAllianceWikiMainPage'] ={
	name = 'RAAllianceWikiMainPage',
	itemAmount = 3,
	icon1 = 'V5AllianceManual_Icon_01',
	title1 = '@AllianceDev',
	icon2 = 'V5AllianceManual_Icon_02',
	title2 = '@PersonalDev',
	icon3 = 'V5AllianceManual_Icon_03',
	title3 = '@WarStrategy',
},
['RABattleEnterPage'] ={
	name = 'RABattleEnterPage',
	itemAmount = 2,
	icon1 = 'V6CommonUI_Icon_Tab_TOH',
	title1 = '@crTitle',
	icon2 = 'V6CommonUI_Icon_Tab_Battle',
	title2 = '@rtsTitle',
},
['RABattleEnterPage_bh_rts'] ={
	name = 'RABattleEnterPage_bh_rts',
	itemAmount = 2,
	icon1 = 'V3CommonUI_Icon_Tab_HeroGacha',
	title1 = '@bhTitle',
	icon2 = 'V6CommonUI_Icon_Tab_Battle',
	title2 = '@rtsTitle',
},
['RABattleEnterPage_bh_cr_rts'] ={
	name = 'RABattleEnterPage_bh_cr_rts',
	itemAmount = 3,
	icon1 = 'V3CommonUI_Icon_Tab_HeroGacha',
	title1 = '@bhTitle',
	icon2 = 'V6CommonUI_Icon_Tab_TOH',
	title2 = '@crTitle',
	icon3 = 'V6CommonUI_Icon_Tab_Battle',
	title3 = '@rtsTitle',
},
['RAActivityMachineAwakeRewardPopUp'] ={
	name = 'RAActivityMachineAwakeRewardPopUp',
	itemAmount = 2,
	icon1 = 'V5CommonUI_Tab_WarMem',
	title1 = '@YuriRankPersonalRewardBtn',
	icon2 = 'V5CommonUI_Tab_WarSearch',
	title2 = '@YuriRankAllianceRewardBtn',
},
['RAHeroCollocationListPage'] ={
	name = 'RAHeroCollocationListPage',
	itemAmount = 3,
	title1 = '@GodCombination',
	title2 = '@BackBone',
	title3 = '@MasterOfFolk',
},
['RAActivityKingAllianceRankPage'] ={
	name = 'RAActivityKingAllianceRankPage',
	itemAmount = 2,
	title1 = '@StrongestAliianceTab1',
	title2 = '@StrongestAliianceTab2',
},
['RAActivityKingAllianceRankPage_Alliance'] ={
	name = 'RAActivityKingAllianceRankPage_Alliance',
	itemAmount = 2,
	title1 = '@StrongestAliianceTab3',
	title2 = '@StrongestAliianceTab4',
},
['RAActivityKingAllianceRankPage_Person'] ={
	name = 'RAActivityKingAllianceRankPage_Person',
	itemAmount = 2,
	title1 = '@StrongestAliianceTab5',
	title2 = '@StrongestAliianceTab6',
},
['RAChatUIPage_Dungenous'] ={
	name = 'RAChatUIPage_Dungenous',
	itemAmount = 4,
	icon1 = 'V4Chat_World',
	title1 = '@World',
	icon2 = 'V4Chat_Alliance',
	title2 = '@AllianceWithTwoBlanks',
	icon3 = 'V6CommonUI_Icon_Tab_Helper',
	title3 = '@Chat_Page_Tab4',
	icon4 = 'V6CommonUI_Icon_Tab_CombatChat',
	title4 = '@ChatTabPageBattleField',
},
['RAChatUIPage_DungenousNoAnchorNoTeamNoAnswer'] ={
	name = 'RAChatUIPage_DungenousNoAnchorNoTeamNoAnswer',
	itemAmount = 3,
	icon1 = 'V4Chat_World',
	title1 = '@World',
	icon2 = 'V4Chat_Alliance',
	title2 = '@AllianceWithTwoBlanks',
	icon3 = 'V6CommonUI_Icon_Tab_CombatChat',
	title3 = '@ChatTabPageBattleField',
},
['RAChatUIPage_AnchorDunge'] ={
	name = 'RAChatUIPage_AnchorDunge',
	itemAmount = 5,
	icon1 = 'V4Chat_World',
	title1 = '@World',
	icon2 = 'V4Chat_Alliance',
	title2 = '@AllianceWithTwoBlanks',
	icon3 = 'V4Chat_Anchor',
	title3 = '@Anchor',
	icon4 = 'V6CommonUI_Icon_Tab_Helper',
	title4 = '@Chat_Page_Tab4',
	icon5 = 'V6CommonUI_Icon_Tab_CombatChat',
	title5 = '@ChatTabPageBattleField',
},
['RAJointMILExplainPopUp'] ={
	name = 'RAJointMILExplainPopUp',
	itemAmount = 2,
	title1 = '@RAJointMILExplainPopUp1',
	title2 = '@RAJointMILExplainPopUp2',
},
['RACrossExpeditionScorePopUp'] ={
	name = 'RACrossExpeditionScorePopUp',
	itemAmount = 4,
	title1 = '@CrossScoreTab1',
	title2 = '@CrossScoreTab2',
	title3 = '@CrossScoreTab5',
	title4 = '@CrossScoreTab3',
},
['RACrossExpeditionRankPopUp'] ={
	name = 'RACrossExpeditionRankPopUp',
	itemAmount = 2,
	title1 = '@Act89PhaseRank',
	title2 = '@Act89AllianceRank',
},
['RAActivityMergeInviteRecordPopUp'] ={
	name = 'RAActivityMergeInviteRecordPopUp',
	itemAmount = 2,
	title1 = '@Act341RecordTab1',
	title2 = '@Act341RecordTab2',
},
['RACrossExpeditionRewardPopUp'] ={
	name = 'RACrossExpeditionRewardPopUp',
	itemAmount = 4,
	title1 = '@CrossLang2',
	title2 = '@CrossRewardTab2',
	title3 = '@CrossRewardTab3',
	title4 = '@CrossLang3',
},
['RACrossServerStrategyPage'] ={
	name = 'RACrossServerStrategyPage',
	itemAmount = 2,
	title1 = '@CrossLang21',
	title2 = '@CrossLang22',
},
['RAMilitaryRankPage'] ={
	name = 'RAMilitaryRankPage',
	itemAmount = 3,
	title1 = '@CrossLang68',
	title2 = '@RAMilitaryRankPageTab2',
	title3 = '@CrossLang86',
},
['RAMilitaryRankRewardPopUp'] ={
	name = 'RAMilitaryRankRewardPopUp',
	itemAmount = 3,
	title1 = '@RAMilitaryRankRewardTab1',
	title2 = '@RAMilitaryRankRewardTab2',
	title3 = '@RAMilitaryRankRewardTab3',
},
['RAAircraftCarrierPage'] ={
	name = 'RAAircraftCarrierPage',
	cellCCBName = 'RAAircraftCarrierTabV3.ccbi',
	itemAmount = 6,
	locateType = -1,  
	title1 = '@TiberiumMainPageTitle',
	title2 = '@TiberiumSeason',
	title3 = '@XQHXTitle',
	title4 = '@CyborgWar',
	title5 = '@JointMILMainPageTitle',
	title6 = '@CrossServerTitle',
},
['RACMNNormalShopPage'] ={
	name = 'RACMNNormalShopPage',
	cellCCBName = 'RAAircraftCarrierTabV3.ccbi',
	itemAmount = 6,
	locateType = 0,  
	title1 = '@ShopName1',
	title2 = '@ShopName2',
	title3 = '@ShopName4',
	title4 = '@ShopName3',
	title5 = '@ShopName5',
	title6 = '@ShopName6',
},
['RAFGYLGuildRankPopUp'] ={
	name = 'RAFGYLGuildRankPopUp',
	-- cellCCBName = 'RAzzPopUpCommonTab2V3.ccbi',
	itemAmount = 2,
	title1 = '@FGYLUILang17_1',
	title2 = '@FGYLUILang17_2',
},
['RAAircraftCarrierGrayMobaPage'] ={
	name = 'RAAircraftCarrierGrayMobaPage',
	cellCCBName = 'RAAircraftCarrierTabV3.ccbi',
	itemAmount = 5,
	title1 = '@TiberiumMainPageTitle',
	title2 = '@TiberiumSeason',
	title3 = '@CyborgWar',
	title4 = '@JointMILMainPageTitle',
	title5 = '@CrossServerTitle',
},
['RASuperLabCombinePage'] ={
	name = 'RASuperLabCombinePage',
	itemAmount = 2,
	icon1 = 'V5CommonUI_Tab_EnergyLab_Syn',
	title1 = '@Compose',
	icon2 = 'V5CommonUI_Tab_EnergyLab_Dcmps',
	title2 = '@Decompose',
},
['RASuperLabMainPage'] ={
	name = 'RASuperLabMainPage',
	tabCCBName = 'mSpecialTabCCB',
	itemAmount = 3,
	title1 = '@Development',
	title2 = '@Support',
	title3 = '@Battle',
},
['RACrossServerPageEnd'] ={
	name = 'RACrossServerPageEnd',
	itemAmount = 3,
	title1 = '@CrossEndTab1',
	title2 = '@CrossEndTab2',
	title3 = '@CrossEndTab3',
},
['RAActivityPresentFlowerRecordPopUp'] ={
	name = 'RAActivityPresentFlowerRecordPopUp',
	itemAmount = 2,
	title1 = '@SendFlowerRecord',
	title2 = '@ReceiveFlowerRecord',
},
['RAActivityPresentFlowerRewardPopUp'] ={
	name = 'RAActivityPresentFlowerRewardPopUp',
	itemAmount = 2,
	title1 = '@SendFlowerRewards',
	title2 = '@ReceiveFlowerRewards',
},
['RAActivityFriendsRecallPopup'] ={
	name = 'RAActivityFriendsRecallPopup',
	itemAmount = 2,
	title1 = '@friendRecallTitle',
	title2 = '@allianceRecallTitle',
},
['RAActivityMachineLabRankPopUp'] ={
	name = 'RAActivityMachineLabRankPopUp',
	itemAmount = 2,
	title1 = '@Act317RankTitle1',
	title2 = '@Act317RankTitle2',
},
['RAActivityBackPlayerAchievePage'] ={
	name = 'RAActivityBackPlayerAchievePage',
	itemAmount = 3,
	title1 = '@return_activity_tip1',
	title2 = '@return_activity_tip2',
	title3 = '@return_activity_tip3',
},
['RAAllianceWarFlagMainPage'] ={
	name = 'RAAllianceWarFlagMainPage',
	itemAmount = 2,
	icon1 = 'V3CommonUI_Icon_Tab_Territory_01',
	title1 = '@WarFlagBuild_new1',
	icon2 = 'V3CommonUI_Icon_Tab_Territory_02',
	title2 = '@WarFlagOccupy_new1',
},
['RAActivityFlagPage'] ={
	name = 'RAActivityFlagPage',
	itemAmount = 3,
	title1 = '@FlagSituation',
	title2 = '@FlagPattern',
	title3 = '@FlagRanKing',
},
['RAActivityFightGodComeRankPopUp'] ={
	name = 'RAActivityFightGodComeRankPopUp',
	itemAmount = 2,
	title1 = '@FlagTip1',
	title2 = '@FlagTip2',
},
['RAMedalWikiMainPage'] ={
	name = 'RAMedalWikiMainPage',
	itemAmount = 3,
	icon1 = 'V5AllianceManual_Icon_01',
	title1 = '@MedalMenuTitle1',
	icon2 = 'V5AllianceManual_Icon_02',
	title2 = '@MedalMenuTitle2',
	icon3 = 'V5AllianceManual_Icon_03',
	title3 = '@MedalMenuTitle3',
},
['RAActivityZeroBuyPage'] ={
	name = 'RAActivityZeroBuyPage',
	itemAmount = 3,
	title1 = '@ZeroBuyTab1',
	title2 = '@ZeroBuyTab2',
	title3 = '@ZeroBuyTab3',
},
['RAFriendsInvitePlayerPage'] ={
	name = 'RAFriendsInvitePlayerPage',
	itemAmount = 2,
	icon1 = 'V3CommonUI_Icon_Tab_AddDetails',
	title1 = '@FriendsFamiliarity',
	icon2 = 'V3CommonUI_Icon_Tab_ResDetails',
	title2 = '@FriendsAlreadyInvited',
},
['RAActivityFightTokenPage'] ={
	name = 'RAActivityFightTokenPage',
	itemAmount = 3,
	title1 = '@FightToken1',
	title2 = '@FightToken2',
	title3 = '@FightToken3',
},
['RASkinAdditionPopUp'] ={
	name = 'RASkinAdditionPopUp',
	itemAmount = 2,
	title1 = '@SkinAdditive_Tip1',
	title2 = '@SkinAdditive_Tip2',
},
['RAActivityTokenTwoPage'] ={
	name = 'RAActivityTokenTwoPage',
	itemAmount = 3,
	title1 = '@Act236Tipe01',
	title2 = '@Act236Tipe02',
	title3 = '@Act236Tipe03',
},
['RABountyHunterPopUp'] ={
	name = 'RABountyHunterPopUp',
	itemAmount = 2,
	title1 = '@BountyHunterList',
	title2 = '@BountyHunterMyReward',
},
['RAWorldTiberiumRulePopUp'] ={
	name = 'RAWorldTiberiumRulePopUp',
	itemAmount = 3,
	title1 = '@TiberiumRulePopUp1',
	title2 = '@TiberiumRulePopUp2',
	title3 = '@TiberiumRulePopUp3',
},
['RAXHJZRulerPopUp'] ={
	name = 'RAXHJZRulerPopUp',
	itemAmount = 3,
	title1 = '@XHJZRulePopUp1',
	title2 = '@XHJZRulePopUp2',
	title3 = '@XHJZRulePopUp3',
},
['RAXQHXRulerPopUp'] ={
	name = 'RAXQHXRulerPopUp',
	itemAmount = 3,
	title1 = '@XQHXUIRulePopUp1',
	title2 = '@XQHXUIRulePopUp2',
	title3 = '@XQHXUIRulePopUp3',
},
['RAWorldXQHXBuildngInfoPopUp']={
	name = 'RAWorldXQHXBuildngInfoPopUp',
	itemAmount = 2,
	title1 = '@YQZZLang1',
	title2 = '@YQZZLang2',
	aniIndex = 2,
},
['RANationalAviationPage'] ={
	name = 'RANationalAviationPage',
	itemAmount = 2,
	title1 = '@RANationalAviationPage1',
	title2 = '@RANationalAviationPage2',
},
['RAYQZZRulePopUp'] ={
	name = 'RAYQZZRulePopUp',
	itemAmount = 3,
	title1 = '@YQZZLang15',
	title2 = '@YQZZLang16',
	title3 = '@YQZZLang17',
},
['RAYQZZRewardsPopUp'] ={
	name = 'RAYQZZRewardsPopUp',
	itemAmount = 3,
	title1 = '@YQZZRewardsPopUp1',
	title2 = '@YQZZRewardsPopUp2',
	title3 = '@YQZZRewardsPopUp3',
},
['RAYQZZAchievePopUp'] ={
	name = 'RAYQZZAchievePopUp',
	itemAmount = 2,
	title1 = '@YQZZAchievePopUp3',
	title2 = '@YQZZAchievePopUp2',
},
['RAYQZZRankPopUp'] ={
	name = 'RAYQZZRankPopUp',
	itemAmount = 2,
	title1 = '@YQZZRankPopUp1',
	title2 = '@YQZZRankPopUp3',
},
['RAYQZZHistoryDetailPopUp'] ={
	name = 'RAYQZZHistoryDetailPopUp',
	itemAmount = 2,
	title1 = '@YQZZRankPopUp2',
	title2 = '@YQZZRankPopUp3',
},
['RAYQZZScorePopUp'] ={
	name = 'RAYQZZScorePopUp',
	itemAmount = 2,
	title1 = '@YQZZScorePopUp2',
	title2 = '@YQZZScorePopUp3',
},
['RAYQZZSeasonScheduleInfoPage'] ={
	name = 'RAYQZZSeasonScheduleInfoPage',
	itemAmount = 3,
	title1 = '@YQZZScheduleInfoTab1',
	title2 = '@YQZZScheduleInfoTab2',
	title3 = '@YQZZScheduleInfoTab3',
},
['RAYQZZRankRewardPopUp'] ={
	name = 'RAYQZZRankRewardPopUp',
	itemAmount = 2,
	title1 = '@YQZZRankPopUp2',
	title2 = '@YQZZRankPopUp3',
},
['YQZZRankPopUpSub'] ={
	name = 'YQZZRankPopUpSub',
	itemAmount = 2,
	title1 = '@YQZZRankPopUpSub1',
	title2 = '@YQZZRankPopUpSub2',
},
['RACrossExpeditionStarPopUp'] ={
	name = 'RACrossExpeditionStarPopUp',
	itemAmount = 4,
	title1 = '@CrossStar1',
	title2 = '@CrossStar2',
	title3 = '@CrossStar3',
	title4 = '@CrossLang55',
},
['RACrossExpeditionStarSeasonPage'] ={
	name = 'RACrossExpeditionStarSeasonPage',
	itemAmount = 3,
	title1 = '@CrossStarSeasonTab1',
	title2 = '@CrossStarSeasonTab2',
	title3 = '@CrossStarSeasonTab3',
},
['RAActivityNEPlanRankPopUp'] ={
	name = 'RAActivityNEPlanRankPopUp',
	itemAmount = 2,
	title1 = '@NEPRankSubTitle1',
	title2 = '@NEPRankRewards',
},
['RAWorldTiberiumDetailPage'] ={
	name = 'RAWorldTiberiumDetailPage',
	itemAmount = 2,
	title1 = '@TiberiumBuildingInfoPage1',
	title2 = '@TiberiumBuildingInfoPage2',
},
['RAWorldTiberiumLabDetailPopUp'] ={
	name = 'RAWorldTiberiumLabDetailPopUp',
	itemAmount = 2,
	title1 = '@TiberiumBuildingLabInfoPage1',
	title2 = '@TiberiumBuildingLabInfoPage2',
},
['RAWorldTiberiumCommandPostPopUp'] ={
	name = 'RAWorldTiberiumCommandPostPopUp',
	itemAmount = 2,
	title1 = '@TiberiumBuildingPostInfoPage1',
	title2 = '@TiberiumBuildingPostInfoPage2',
},
['RAActivityFestivalPopUp'] ={
	name = 'RAActivityFestivalPopUp',
	itemAmount = 3,
},
['RAActivityEnergyAggregationPopUp'] ={
	name = 'RAActivityEnergyAggregationPopUp',
	itemAmount = 3,
},
['RAActivityEnergyAggregationTwoPopUp'] ={
	name = 'RAActivityEnergyAggregationTwoPopUp',
	itemAmount = 3,
},
['RAActivityMachineAwakePageV3'] ={
	name = 'RAActivityMachineAwakePageV3',
	itemAmount = 2,
	title1 = '@Activity_Tip1',
	title2 = '@Activity_Tip3',
},
['RAActivityFestivalTwoPopUp'] ={
	name = 'RAActivityFestivalTwoPopUp',
	itemAmount = 3,
},
['RAActivityYRStatusOpen'] ={
	name = 'RAActivityYRStatusOpen',
	itemAmount = 3,
	title1 = '@Activity_Tip1',
	title2 = '@Activity_Tip2',
	title3 = '@Activity_Tip3',
},
['RAActivityMachineAwakePage'] ={
	name = 'RAActivityMachineAwakePage',
	itemAmount = 3,
	title1 = '@Activity_Tip1',
	title2 = '@Activity_Tip2',
	title3 = '@Activity_Tip3',
},
['RAActivityBloodCorpsPage'] ={
	name = 'RAActivityBloodCorpsPage',
	itemAmount = 2,
	title1 = '@BloodCorpsPower',
	title2 = '@BloodCorpsRankUp',
},
['RAActivityFragmentExchangePage'] ={
	name = 'RAActivityFragmentExchangePage',
	itemAmount = 2,
	title1 = '@Activity_Tip4',
	title2 = '@Activity_Tip5',
},
['RAXZQRewardPage'] ={
	name = 'RAXZQRewardPage',
	tabCCBName = 'mCommonTab3CCB',
	itemAmount = 2,
	title1 = '@XZQAwardPage1Title',
	title2 = '@XZQAwardPage2Title',
},

['RAXZQDetailPage'] ={
	name = 'RAXZQDetailPage',
	tabCCBName = 'mCommonTab3CCB',
	itemAmount = 3,
	title1 = '@XZQPointInfoPageTitle1',
	title2 = '@XZQPointInfoPageTitle2',
	title3 = '@XZQPointInfoPageTitle3',
},
['RAActivityTimeLimitDropPage'] ={
	name = 'RAActivityTimeLimitDropPage',
	itemAmount = 2,
	title1 = '@TimeDropReward',
	title2 = '@TimeDropRank',
},
['RADressGiveItemListPopUp'] ={
	name = 'RADressGiveItemListPopUp',
	itemAmount = 5,
	title1 = '@Skin_Give_Tip28',
	title2 = '@Skin_Give_Tip29',
	title3 = '@Skin_Give_Tip31',
	title4 = '@Skin_Give_Tip32',
	title5 = '@Skin_Give_Tip30',
},
['RADressAskMainPopUp'] ={
	name = 'RADressAskMainPopUp',
	itemAmount = 5,
	title1 = '@Skin_Give_Tip28',
	title2 = '@Skin_Give_Tip29',
	title3 = '@Skin_Give_Tip31',
	title4 = '@Skin_Give_Tip32',
	title5 = '@Skin_Give_Tip30',
},
['RADressGiveSelectPopUp'] ={
	name = 'RADressGiveSelectPopUp',
	itemAmount = 2,
	title1 = '@Skin_Give_Tip12',
	title2 = '@Skin_Give_Tip13',
},
['RAFriendGuardGiveSelectPopUp'] ={
	name = 'RAFriendGuardGiveSelectPopUp',
	itemAmount = 2,
	title1 = '@Skin_Give_Tip12',
	title2 = '@Skin_Give_Tip13',
},

['RAActivityPromoterPage'] ={
	name = 'RAActivityPromoterPage',
	itemAmount = 3,
	title1 = '@Act124_Page_1',
	title2 = '@Act124_Page_2',
	title3 = '@Act124_Page_3',
},
['RAAircraftCarrieriOSVersionPage'] ={
	name = 'RAAircraftCarrieriOSVersionPage',
	itemAmount = 2,
	title1 = '@JointMILMainPageTitle',
	title2 = '@CrossServerTitle',
},
['RAActivityAllyBeatBackPage'] ={
	name = 'RAActivityAllyBeatBackPage',
	itemAmount = 2,
	title1 = '@AllyBeatTakeReward',
	title2 = '@AllyBeatExchange',
},
['RAActivityNewWayPage'] ={
	name = 'RAActivityNewWayPage',
	itemAmount = 2,
	title1 = '@RAAct339Lang1',
	title2 = '@RAAct339Lang2',
},
['RANewAllianceWarPage_2'] ={
	name = 'RANewAllianceWarPage_2',
	itemAmount = 2,
	title1 = '@JoinAttack',
	title2 = '@JoinDefense',
},
['RANewAllianceWarPage_3'] ={
	name = 'RANewAllianceWarPage_3',
	itemAmount = 3,
	title1 = '@JoinAttack',
	title2 = '@JoinDefense',
	title3 = '@JoinRevenge',
},
['RAActivityCommonExchangePageTwo'] ={
	name = 'RAActivityCommonExchangePageTwo',
	itemAmount = 2,
	title1 = '@universal_exchange_two',
	title2 = '@universal_package_two',
},
['RAActivityHeroTrialPage'] ={
	name = 'RAActivityHeroTrialPage',
	itemAmount = 2,
	title1 = '@Act128_Tab_1',
	title2 = '@Act128_Tab_2',
},
['RAActivityBlackTechPage'] ={
	name = 'RAActivityBlackTechPage',
	itemAmount = 2,
	title1 = '@Act131Tip1',
	title2 = '@Act131Tip2',
},
['RAArmourMainPage'] ={
	name = 'RAArmourMainPage',
	itemAmount = 3,
	title1 = '@ArmourMO',
	title2 = '@armoursuit',
	title3 = '@EquipImmortal_TabEcho',
},
['RAArmourUpgradePage'] ={
	name = 'RAArmourUpgradePage',
	itemAmount = 2,
	title1 = '@ArmourLevel',
	title2 = '@ArmourInherit',
},
['RAArmourRewardPreviewPopUp'] ={
	name = 'RAArmourRewardPreviewPopUp',
	itemAmount = 4,
	title1 = '@ArmourTitle1',
	title2 = '@ArmourTitle2',
	title3 = '@ArmourTitle3',
	title4 = '@ArmourTitle4',
},
['RAArmourManualPopUp'] ={
	name = 'RAArmourManualPopUp',
	itemAmount = 3,
	title1 = '@ArmourExplainTitle1',
	title2 = '@ArmourExplainTitle2',
	title3 = '@ArmourExplainTitle3',
},
['RABountyHunterRulePopUp'] ={
	name = 'RABountyHunterRulePopUp',
	itemAmount = 2,
	title1 = '@Act121_Tab_1',
	title2 = '@Act121_Tab_2',
},
['RAActivityPresentFlowerPage'] ={
	name = 'RAActivityPresentFlowerPage',
	itemAmount = 3,
	title1 = '@ActivityDetail',
	title2 = '@SendFlowerRank',
	title3 = '@ReceiveFlowerRank',
},
['RAActivityYRRankRewardPopupPage'] ={
	name = 'RAActivityYRRankRewardPopupPage',
	itemAmount = 2,
	title1 = '@YuriRankPersonalRewardBtn',
	title2 = '@YuriRankAllianceRewardBtn',
},
['RAActivityFullyArmedPage'] ={
	name = 'RAActivityFullyArmedPage',
	itemAmount = 3,
	title1 = '@Act132_Tab_1',
	title2 = '@Act132_Tab_2',
	title3 = '@Act132_Tab_3',
},
['RAActivityTournamentRankPopUp'] ={
	name = 'RAActivityTournamentRankPopUp',
	itemAmount = 3,
	title1 = '@ChampionshipSectionAward',
	title2 = '@ChampionshipGuildRank',
	title3 = '@ChampionshipPersonalRank',
},
['RAActivitySuperPowerLabPage'] ={
	name = 'RAActivitySuperPowerLabPage',
	itemAmount = 3,
	title1 = '@SuperPowerMyCollect',
	title2 = '@SuperPowerPersonRank',
	title3 = '@SuperPowerAlliRank',
},
['RAActivityFighterPuzzlePage'] ={
	name = 'RAActivityFighterPuzzlePage',
	itemAmount = 2,
	title1 = '@Act133_Tab_1',
	title2 = '@Act133_Tab_2',
},
['RAActivityFighterPuzzleTwoPage'] ={
	name = 'RAActivityFighterPuzzleTwoPage',
	itemAmount = 2,
	title1 = '@Act282_Tab_1',
	title2 = '@Act282_Tab_2',
},
['RAWorldWarMainPage'] ={
	name = 'RAWorldWarMainPage',
	itemAmount = 2,
	title1 = '@AF_TabTitle',
	title2 = '@AF_TabSendgift',
},
['RAWorldWarMgrPage'] ={
	name = 'RAWorldWarMgrPage',
	itemAmount = 3,
	title1 = '@AF_TabDetails',
	title2 = '@AF_TabWarehouse',
	title3 = '@AF_TabStrategy',
},
['RAHeroMainPage_Skin'] ={
	name = 'RAHeroMainPage_Skin',
	itemAmount = 5,
	icon1 = 'V3CommonUI_Icon_Tab_Synopsis',
	title1 = '@TabBtnLabel1',
	icon2 = 'V3CommonUI_Icon_Tab_Upgrade',
	title2 = '@TabBtnLabel2',
	icon3 = 'V3CommonUI_Icon_Tab_PromoteStar',
	title3 = '@TabBtnLabel3',
	icon4 = 'V3CommonUI_Icon_Tab_HeroSkill',
	title4 = '@TabBtnLabel4',
	icon5 = 'V6CommonUI_Icon_Tab_HeroSkin',
	title5 = '@TabBtn6',
},
['RAHeroMainPage2_Skin'] ={
	name = 'RAHeroMainPage2_Skin',
	itemAmount = 5,
	icon1 = 'V3CommonUI_Icon_Tab_Synopsis',
	title1 = '@TabBtnLabel1',
	icon2 = 'V3CommonUI_Icon_Tab_Upgrade',
	title2 = '@TabBtnLabel2',
	icon3 = 'V3CommonUI_Icon_Tab_HeroTalent',
	title3 = '@TabBtnLabel5',
	icon4 = 'V3CommonUI_Icon_Tab_HeroSkill',
	title4 = '@TabBtnLabel4',
	icon5 = 'V6CommonUI_Icon_Tab_HeroSkin',
	title5 = '@TabBtn6',
},
['RAAllianceShopRecordPage'] ={
	name = 'RAAllianceShopRecordPage',
	itemAmount = 2,
	title1 = '@BuyRecord',
	title2 = '@AddGoodsRecord',
},
['RATroopBuffSelectPopUp'] ={
	name = 'RATroopBuffSelectPopUp',
	cellCCBName = 'RATroopChargeQUTabNodeV3.ccbi',
    itemAmount = 7,
    title1 = '@TroopSelectBuffStrategy',
    title2 = '@GloryHeroEquipmentPage',
    title3 = '@TroopSelectBuffSuperLab',
    title4 = '@BuildingSkin',
    title5 = '@TroopSelectBuffGain',
    title6 = '@ManhattanSW_Deploy_AtkDes2',
    title7 = '@ManhattanSW_Deploy_DefDes2',
},
['RATroopBuffSelectPopUpWithMechaCore'] ={
	name = 'RATroopBuffSelectPopUpWithMechaCore', 
	cellCCBName = 'RATroopChargeQUTabNodeV3.ccbi',
    itemAmount = 8,
    title1 = '@TroopSelectBuffStrategy',
    title2 = '@GloryHeroEquipmentPage',
    title3 = '@TroopSelectBuffSuperLab',
    title4 = '@BuildingSkin',
    title5 = '@TroopSelectBuffGain',
    title6 = '@ManhattanSW_Deploy_AtkDes2',
    title7 = '@ManhattanSW_Deploy_DefDes2',
    title8 = '@RAMechaCoreLang61',
},
['RATBSeasonRewardPopUp'] ={
	name = 'RATBSeasonRewardPopUp',
	itemAmount = 4,
	title1 = '@TiberiumGameAward',
	title2 = '@TiberiumBattleAward',
	title3 = '@TiberiumSeasonGuildAward',
	title4 = '@TiberiumSeasonPersonalAward',
},
['RAYQZZSeasonRewardPopUp'] ={
	name = 'RAYQZZSeasonRewardPopUp',
	itemAmount = 2,
	title1 = '@RAYQZZSeasonRewardPopUpTab1',
	title2 = '@RAYQZZSeasonRewardPopUpTab3',
},
['RAStarWarMainRoadRewardPopUp'] ={
	name = 'RAStarWarMainRoadRewardPopUp',
	itemAmount = 3,
	title1 = '@RAStarWarMainRoadRewardPopUpTab1',
	title2 = '@RAStarWarMainRoadRewardPopUpTab2',
	title3 = '@RAStarWarMainRoadRewardPopUpTab3',
},
['RATBSeasonZonePage'] ={
	name = 'RATBSeasonZonePage',
	itemAmount = 2,
	title1 = '@TBSeasontitle2',
	title2 = '@TBSeasontitle1',
},
['RATBSeasonMatchPage'] ={
	name = 'RATBSeasonMatchPage',
	itemAmount = 2,
	title1 = '@TBSeasonMatchPageTitle1',
	title2 = '@TBSeasonMatchPageTitle2',
},
['RAActivityMilitaryPreparePage'] ={
	name = 'RAActivityMilitaryPreparePage',
	itemAmount = 4,
},
['RAActivityALCarnivalPage'] ={
	name = 'RAActivityALCarnivalPage',
	itemAmount = 3,
	title1 = '@alliance_active_reward2',
	title2 = '@alliance_active_quest',
	title3 = '@alliance_active_devote',
},
['RAActWeekCalendarPage'] ={
	name = 'RAActWeekCalendarPage',
	itemAmount = 2,
	title1 = '@ActivityWeekCalendarTab1',
	title2 = '@ActivityWeekCalendarTab2',
},
['RALimitTimeLoginPage'] ={
	name = 'RALimitTimeLoginPage',
	itemAmount = 2,
	title1 = '@Activity148Tab1',
	title2 = '@Activity148Tab2',
},
['RAStarWarMatchPage'] ={
	name = 'RAStarWarMatchPage',
	itemAmount = 2,
	title1 = '@SWSeasonZoneRank',
	title2 = '@SWSeasonZoneServer',
},
['RAActivityMedalActionPage'] ={
	name = 'RAActivityMedalActionPage',
	itemAmount = 2,
	title1 = '@ActivityMedalActionTab1',
	title2 = '@ActivityMedalActionTab2',
},
-- ['RAActivityDivideGoldPage'] ={
-- 	name = 'RAActivityDivideGoldPage',
-- 	itemAmount = 2,
-- 	title1 = '@ActivityDivideGoldTab1',
-- 	title2 = '@ActivityDivideGoldTab2',
-- },
['RAActivityKoiPage'] ={
	name = 'RAActivityKoiPage',
	itemAmount = 2,
	title1 = '@ActivityKoiPageTab1',
	title2 = '@ActivityKoiPageTab2',
},
['RAStarWarMainPage'] ={
	name = 'RAStarWarMainPage',
	itemAmount = 2,
	title1 = '@sw_tabtitle_1',
	title2 = '@sw_tabtitle_2',
},
['RAActivityHeroEvolutionPopUp'] ={
	name = 'RAActivityHeroEvolutionPopUp',
	itemAmount = 2,
	title1 = '@PathEvolution12',
	title2 = '@PathEvolution13',
},
['RASimulateAwardPopUp'] ={
	name = 'RASimulateAwardPopUp',
	itemAmount = 2,
	title1 = '@SimulateSW_TabTitle',
	title2 = '@SimulateSW_TabSendgift',
},
['RAActivityFlightPlanPage'] ={
	name = 'RAActivityFlightPlanPage',
	itemAmount = 2,
	title1 = '@celebrationPlan',
	title2 = '@celebrationTask',
},
['RABlackListPage'] ={
	name = 'RABlackListPage',
	itemAmount = 2,
	title1 = '@BlackListTab1',
	title2 = '@BlackListTab2',
},
['RAActivityDailyRechargeAcc157Page'] ={
	name = 'RAActivityDailyRechargeAcc157Page',
	itemAmount = 2,
	title1 = '@Cumulative1',
	title2 = '@Cumulative2',
},
['RACrossChargeRankPopUp'] ={
	name = 'RACrossChargeRankPopUp',
	itemAmount = 2,
	title1 = '@crossChargeTab1',
	title2 = '@crossChargeTab2',
},
['RACrossChargeRankRewardPopUp'] ={
	name = 'RACrossChargeRankRewardPopUp',
	itemAmount = 2,
	title1 = '@crossChargeTab1',
	title2 = '@crossChargeTab2',
},
['RATaxDistributeSelectPopUp'] ={
	name = 'RATaxDistributeSelectPopUp',
	itemAmount = 2,
	title1 = '@CrossSelect1',
	title2 = '@CrossSelect2',
},
['RAActivityDarkWarriorPage'] ={
	name = 'RAActivityDarkWarriorPage',
	itemAmount = 2,
	title1 = '@Act133_Tab_1',
	title2 = '@Act133_Tab_2',
},
['RAActivityAllianceWishPage'] ={
	name = 'RAActivityAllianceWishPage',
	itemAmount = 2,
	title1 = '@Act298_Tab_1',
	title2 = '@Act298_Tab_2',
},
['RAActivityBaseBuildPage'] ={
	name = 'RAActivityBaseBuildPage',
	itemAmount = 2,
	title1 = '@Act161_Tab_1',
	title2 = '@Act161_Tab_2',
},
['RAActivityJoyBuyPage'] ={
	name = 'RAActivityJoyBuyPage',
	itemAmount = 2,
	title1 = '@Act188Tipe01',
	title2 = '@Act188Tipe02',
},
['RAActivityEquipBlackMarketPage'] ={
	name = 'RAActivityEquipBlackMarketPage',
	itemAmount = 2,
	title1 = '@Act165_Tab_1',
	title2 = '@Act165_Tab_2',
},
['RAChristmasBattleRankPopUp'] ={
	name = 'RAChristmasBattleRankPopUp',
	itemAmount = 2,
	title1 = '@Act163_tab6',
	title2 = '@Act163_tab7',
},
['RAChristmasBattleRewardPopUp'] ={
	name = 'RAChristmasBattleRewardPopUp',
	itemAmount = 2,
	title1 = '@Act163_tab1',
	title2 = '@Act163_tab2',
},
['RAChristmasBattleRankRewardPopUp'] ={
	name = 'RAChristmasBattleRankRewardPopUp',
	itemAmount = 2,
	title1 = '@Act163_tab6',
	title2 = '@Act163_tab7',
},
['RAActivitySnowBallRewardsPage'] ={
	name = 'RAActivitySnowBallRewardsPage',
	itemAmount = 3,
	title1 = '@Act164RewardTab3',
	title2 = '@Act164RewardTab1',
	title3 = '@Act164RewardTab2',
},
['RAActivitySnowBallScoreInfoPage'] ={
	name = 'RAActivitySnowBallScoreInfoPage',
	itemAmount = 2,
	title1 = '@Act164InfoTab1',
	title2 = '@Act164InfoTab2',
},
['RAActivitySnowBallRankPage'] ={
	name = 'RAActivitySnowBallRankPage',
	itemAmount = 2,
	title1 = '@Act164RankTab1',
	title2 = '@Act164RankTab2',
},
['RAActivityDestinyRevolverPage'] ={
	name = 'RAActivityDestinyRevolverPage',
	itemAmount = 2,
	title1 = '@Act166InfoTab1',
	title2 = '@Act166InfoTab2',
},
['RAHeroRelationPage'] ={
	name = 'RAHeroRelationPage',
	itemAmount = 2,
	title1 = '@HeroRelation1',
	title2 = '@HeroRelation2',
},
['RAHeroRelationPopUp'] ={
	name = 'RAHeroRelationPopUp',
	itemAmount = 5,
	icon1 = 'V3CommonUI_Icon_Tab_All',
	title1 = '@TabBtn1',
	icon2 = 'V3CommonUI_Icon_Tab_Military',
	title2 = '@TabBtn2',
	icon3 = 'V3CommonUI_Icon_Tab_Resources',
	title3 = '@TabBtn3',
	icon4 = 'V3CommonUI_Icon_Tab_Train',
	title4 = '@TabBtn4',
	icon5 = 'V3CommonUI_Icon_Tab_HeroAppoint',
	title5 = '@attrName1011',
},
['RAHeroRelationPopUpSubPopUp'] = {
	name = 'RAHeroRelationPopUpSubPopUp',
	itemAmount = 6,
	title1 = '@AllHeroFilter',
	title2 = '@TankHeroFilter',
	title3 = '@InfantryHeroFilter',
	title4 = '@AirplaneHeroFilter',
	title5 = '@ChariotHeroFilter',
	title6 = '@UniversalHeroFilter',
},
['RAWorldCyborgDetailPage'] ={
	name = 'RAWorldCyborgDetailPage',
	itemAmount = 2,
	title1 = '@CyborgBuildingInfoPage1',
	title2 = '@CyborgBuildingInfoPage2',
},
['RAWorldMobaBuildDetailPage'] ={
	name = 'RAWorldMobaBuildDetailPage',
	itemAmount = 2,
	title1 = '@WorldMobaBuildingInfoPage1',
	title2 = '@WorldMobaBuildingInfoPage2',
},
['RAWorldMobaBuildAltarDetailPage'] ={
	name = 'RAWorldMobaBuildAltarDetailPage',
	itemAmount = 2,
	title1 = '@WorldMobaBuildingInfoPage1',
	title2 = '@WorldMobaBuildingInfoPage2',
},
['RACyborgRewardInfoPopUp'] ={
	name = 'RACyborgRewardInfoPopUp',
	itemAmount = 3,
	title1 = '@CyborgText2',
	title2 = '@CyborgText3',
	title3 = '@CyborgText4',
},
['RACyborgSeasonInfoPage'] ={
	name = 'RACyborgSeasonInfoPage',
	itemAmount = 4,
	title1 = '@cyborgSeasontitle1',
	title2 = '@cyborgSeasontitle2',
	title3 = '@cyborgSeasontitle3',
	title4 = '@cyborgSeasontitle4',
},
['RACyborgHistoryPopUp'] ={
	name = 'RACyborgHistoryPopUp',
	itemAmount = 2,
	title1 = '@cyborgInfoTtile1',
	title2 = '@cyborgInfoTtile2',
},
['RACyborgRankPage'] ={
	name = 'RACyborgRankPage',
	itemAmount = 2,
	title1 = '@cyborgRankTab1',
	title2 = '@cyborgRankTab2',
},
['RAWorldCyborgRulePopUp'] ={
	name = 'RAWorldCyborgRulePopUp',
	itemAmount = 3,
	title1 = '@CyborgRulePopUp1',
	title2 = '@CyborgRulePopUp2',
	title3 = '@CyborgRulePopUp3',
},
['RAWorldCyborgBuffPopUp'] ={
	name = 'RAWorldCyborgBuffPopUp',
	itemAmount = 4,
	title1 = '@CyborgText16',
	title2 = '@CyborgText15',
	title3 = '@CyborgText17',
	title4 = '@CyborgText18',
},
['RAMobaWarRulePopUp'] ={
	name = 'RAMobaWarRulePopUp',
	itemAmount = 3,
	title1 = '@CyborgRulePopUp1',
	title2 = '@CyborgRulePopUp2',
	title3 = '@CyborgRulePopUp3',
},
['RAActivityResourceDefencePage'] ={
	name = 'RAActivityResourceDefencePage',
	itemAmount = 3,
	title1 = '@Act167_TabName1',
	title2 = '@Act167_TabName2',
	title3 = '@Act167_TabName3',
},
['RAActivityHeroPlanPage'] ={
	name = 'RAActivityHeroPlanPage',
	itemAmount = 2,
	title1 = '@Act168Tipe01',
	title2 = '@Act168Tipe02',
},
['RAMailFightEffPopUp'] ={
	name = 'RAMailFightEffPopUp',
	itemAmount = 2,
	title1 = '@EffPopUpTipe01',
	title2 = '@EffPopUpTipe02',
},
['RAMailFightEffPopUp_activity'] ={
	name = 'RAMailFightEffPopUp_activity',
	itemAmount = 2,
	title1 = '@EffPopUpTipe03',
	title2 = '@EffPopUpTipe04',
},
['RAChatUIPage_Dungenous_Team'] ={
	name = 'RAChatUIPage_Dungenous_Team',
	itemAmount = 4,
	icon1 = 'V4Chat_World',
	title1 = '@World',
	icon2 = 'V4Chat_Alliance',
	title2 = '@AllianceWithTwoBlanks',
	icon3 = 'V6CommonUI_Icon_Tab_Helper',
	title3 = '@ChatTabPageTeamChannel',
	icon4 = 'V6CommonUI_Icon_Tab_CombatChat',
	title4 = '@ChatTabPageBattleField',
},
['RAChatUIPage_Dungenous_Nation_Team'] ={
	name = 'RAChatUIPage_Dungenous_Nation_Team',
	itemAmount = 3,
	icon1 = 'V4Chat_World',
	title1 = '@World',
	icon2 = 'V6CommonUI_Icon_Tab_BattleSquad',
	title2 = '@ChatTabTeamChannel',
	icon3 = 'V6CommonUI_Icon_Tab_CombatChat',
	title3 = '@ChatTabBattleField',
},
['RAChatUIPage_AnchorDunge_Team'] ={
	name = 'RAChatUIPage_AnchorDunge_Team',
	itemAmount = 5,
	icon1 = 'V4Chat_World',
	title1 = '@World',
	icon2 = 'V4Chat_Alliance',
	title2 = '@AllianceWithTwoBlanks',
	icon3 = 'V4Chat_Anchor',
	title3 = '@Anchor',
	icon4 = 'V6CommonUI_Icon_Tab_Helper',
	title4 = '@ChatTabPageTeamChannel',
	icon5 = 'V6CommonUI_Icon_Tab_CombatChat',
	title5 = '@ChatTabPageBattleField',
},
['RAChatUIPage_Moba_Team'] ={
	name = 'RAChatUIPage_Moba_Team',
	itemAmount = 2,
	icon1 = 'V6CommonUI_Icon_Tab_Helper',
	title1 = '@ChatTabPageTeamChannel',
	icon2 = 'V6CommonUI_Icon_Tab_CombatChat',
	title2 = '@ChatTabPageBattleField',
},
['RAActivityNewVersionPage'] ={
	name = 'RAActivityNewVersionPage',
	itemAmount = 2,
	title1 = '@Act172Tipe01',
	title2 = '@Act172Tipe02',
},
['RAActivityBackPlayerAchieveNewPage'] ={
	name = 'RAActivityBackPlayerAchieveNewPage',
	itemAmount = 3,
	title1 = '@return_activity_tip1',
	title2 = '@return_activity_tip2',
	title3 = '@return_activity_tip3',
},
['RAActivityBackPlayerGrassBackPage'] ={
	name = 'RAActivityBackPlayerGrassBackPage',
	itemAmount = 4,
	title1 = '@Act176Tipe01',
	title2 = '@Act176Tipe02',
	title3 = '@Act176Tipe03',
	title4 = '@Act176Tipe04',
},
['RAActivityExchangeSkinPage'] ={
	name = 'RAActivityExchangeSkinPage',
	itemAmount = 3,
	title1 = '@Act189Tipe01',
	title2 = '@Act189Tipe02',
	title3 = '@Act189Tipe03',
},
['RAActivityEnergyRollingPage'] ={
	name = 'RAActivityEnergyRollingPage',
	itemAmount = 2,
	title1 = '@Act191Title1',
	title2 = '@Act191Title2',
},
['RAActivityEnergyRollingRankPopUp_Rank'] ={
	name = 'RAActivityEnergyRollingRankPopUp_Rank',
	itemAmount = 2,
	title1 = '@Act191_PersonalScore',
	title2 = '@Act191_GuildScore',
},
['RAActivityEnergyRollingRankPopUp_Reward'] ={
	name = 'RAActivityEnergyRollingRankPopUp_Reward',
	itemAmount = 2,
	title1 = '@Act191_PersonalAward',
	title2 = '@Act191_GuildAward',
},
['RAActivityVirtualLabPage'] ={
	name = 'RAActivityVirtualLabPage',
	itemAmount = 2,
	title1 = '@Act198TabTitle1',
	title2 = '@Act198TabTitle2',
},
['RAWorldWarMgrStrategyFile'] ={
	name = 'RAWorldWarMgrStrategyFile',
	itemAmount = 2,
	title1 = '@AF_TabSkill1',
	title2 = '@AF_TabSkill2',
},
['RAActivityMedalInvestPage'] ={
	name = 'RAActivityMedalInvestPage',
	itemAmount = 3,
	title1 = '@Act201Tipe01',
	title2 = '@Act201Tipe02',
	title3 = '@Act201Tipe03',
},
['RAActivityEquipmentInvestPage'] ={
	name = 'RAActivityEquipmentInvestPage',
	itemAmount = 3,
	title1 = '@Act288Tipe01',
	title2 = '@Act288Tipe02',
	title3 = '@Act288Tipe03',
},
['RAActivityLaboratoryInvestPage'] ={
	name = 'RAActivityLaboratoryInvestPage',
	itemAmount = 3,
	title1 = '@Act201Tipe01',
	title2 = '@Act201Tipe02',
	title3 = '@Act201Tipe03',
},
['RAActivitySuperSoldierInvestPage'] ={
	name = 'RAActivitySuperSoldierInvestPage',
	itemAmount = 3,
	title1 = '@Act201Tipe01',
	title2 = '@Act201Tipe02',
	title3 = '@Act201Tipe03',
},
['RAAllianceWarZonePage'] = {
	name = 'RAAllianceWarZonePage',
	itemAmount = 2,
	title1 = '@AllianceWarZoneTabName1',
	title2 = '@AllianceWarZoneTabName2',
},
['RAActivityOverlordBattlePage'] = {
	name = 'RAActivityOverlordBattlePage',
	itemAmount = 2,
	title1 = '@Act205TabName1',
	title2 = '@Act205TabName2',
},
['RAActivityBeginTokenPage'] ={
	name = 'RAActivityBeginTokenPage',
	itemAmount = 3,
	title1 = '@NewFightToken1',
	title2 = '@FightToken2',
	title3 = '@FightToken3',
},
['RAActivityOFSelectRewardPopUp'] ={
	name = 'RAActivityOFSelectRewardPopUp',
	itemAmount = 2,
	title1 = '@OrdinaryAwardPool',
	title2 = '@SpcialAwardPool',
},
['RAActivityGreetingsPage'] ={
	name = 'RAActivityGreetingsPage',
	itemAmount = 2,
	title1 = '@Act219Title1',
	title2 = '@Act219Title2',
},
['RATBHofAllianceOtherHonorPage'] ={
	name = 'RATBHofAllianceOtherHonorPage',
	itemAmount = 3,
	title1 = '@TBHofTtile6',
	title2 = '@TBHofTtile7',
	title3 = '@TBHofTtile8',
},
['RAActivityBFTreasurePage'] ={
	name = 'RAActivityBFTreasurePage',
	itemAmount = 3,
	title1 = '@ActArmsTab1',
	title2 = '@ActArmsTab2',
	title3 = '@CombatEscort03',
},
['RAActivityTokenEquipPage'] ={
	name = 'RAActivityTokenEquipPage',
	itemAmount = 2,
	title1 = '@Act261Tipe01',
	title2 = '@Act261Tipe02',
},
['RARAActivityDouble11ExchangeRankPopUp'] ={
	name = 'RARAActivityDouble11ExchangeRankPopUp',
	itemAmount = 2,
	title1 = '@ChatAnchorRankTxt1',
	title2 = '@RewardRank2',
},
['RAActivityDouble12PeakHonourRankPopUp'] ={
	name = 'RAActivityDouble12PeakHonourRankPopUp',
	itemAmount = 2,
	title1 = '@TimeDropRankNum',
	title2 = '@RewardRank2',
},
['RAPointSprintRankPopUp'] ={
	name = 'RAPointSprintRankPopUp',
	itemAmount = 2,
	title1 = '@TimeDropRankNum',
	title2 = '@RewardRank2',
},
['RAActivityStarExploreRankPopUp'] = {
	name = 'RAActivityStarExploreRankPopUp',
	itemAmount = 2,
	title1 = '@TimeDropRankNum',
	title2 = '@RewardRank2',
},
['RAActivityDouble12PeakHonourGetAwardPopUp'] ={
	name = 'RAActivityDouble12PeakHonourGetAwardPopUp',
	itemAmount = 2,
	title1 = '@TiberiumSeasonPersonalAward',
	title2 = '@TiberiumSeasonGuildAward',
},
['RAActivityNewZeroBuyPage'] ={
	name = 'RAActivityNewZeroBuyPage',
	itemAmount = 3,
	title1 = '@ZeroBuyTab1',
	title2 = '@ZeroBuyTab2',
	title3 = '@ZeroBuyTab3',
},
['RAActivityDouble11ExchangeRankPopUp'] ={
	name = 'RAActivityDouble11ExchangeRankPopUp',
	itemAmount = 2,
	title1 = '@ChatAnchorRankTxt1',
	title2 = '@RewardRank2',
},
['RAPersonalInfoPage'] ={
	name = 'RAPersonalInfoPage',
	tabCCBName = 'RAzzPageCommonTab3V3.ccbi',
	itemAmount = 3,
	title1 = '@RASettingPrivacyTab1',
	title2 = '@RASettingPrivacyTab2',
	title3 = '@RASettingPrivacyTab3',
},
['RAPersonalInfoPage_101'] ={
	name = 'RAPersonalInfoPage_101',
	tabCCBName = 'RAzzPageCommonTab2V3.ccbi',
	itemAmount = 2,
	title1 = '@RASettingPrivacyTab1',
	title2 = '@RASettingPrivacyTab2',
},
['RAActivityPFSelectRewardPopUp'] ={
	name = 'RAActivityPFSelectRewardPopUp',
	itemAmount = 2,
	title1 = '@OrdinaryAwardPool',
	title2 = '@SpcialAwardPool',
},
['RAFriendsRecallTab1CCB'] = {
	name = 'RAFriendsRecallTab1CCB',
	itemAmount = 2,
	title1 = '@recall_friend_tip2',
	title2 = '@recall_friend_tip3',
	aniIndex = 4,

},
['RAFriendsRecallTab2CCB'] = {
	name = 'RAFriendsRecallTab2CCB',
	itemAmount = 3,
	title1 = '@allianceRecallInvitation',
	title2 = '@allianceRecallNumber',
	title3 = '@allianceRecallTask',
	aniIndex = 4,
},
['RAFundCollectionPage'] = {
	name = 'RAFundCollectionPage',
	itemAmount = 3,
	title1 = '@Act285Tlang1',
	title2 = '@Act285Tlang2',
	title3 = '@Act285Tlang3',
	aniIndex = 3,
},
['RAFavorabilityPopUp'] = {
	name = 'RAFavorabilityPopUp',
	itemAmount = 2,
	title1 = '@travelShopFriendRewardTag',
	title2 = '@travelShopFriendRewardTipsTag',
	aniIndex = 2,
},
['RAActivityLossPage'] = {
	name = 'RAActivityLossPage',
	itemAmount = 2,
	title1 = '@Act290Tlang1',
	title2 = '@Act290Tlang2',
	aniIndex = 2,
},
["RAActivityDressTreasurePage"] ={
    name = "RAActivityDressTreasurePage",
	itemAmount = 2,
	title1 = '@Act289Tlang1',
	title2 = '@Act289Tlang2',
},
["RAActivityChangeServerListPage"] ={
    name = "RAActivityChangeServerListPage",
	itemAmount = 3,
	title1 = '@MigrantLang52',
	title2 = '@MigrantLang53',
	title3 = '@MigrantLang54',
},

["RAActivityChangeServerRankPage"] ={
    name = "RAActivityChangeServerRankPage",
	itemAmount = 2,
	title1 = '@MigrantLang47',
	title2 = '@MigrantLang48',
},
["RAActivityBackChangeServerRankPage"] ={
    name = "RAActivityBackChangeServerRankPage",
	itemAmount = 2,
	title1 = '@Act357_rankTab1',
	title2 = '@Act357_rankTab2',
},
["RANBuildDetailListPopUp"] ={
    name = "RANBuildDetailListPopUp",
	itemAmount = 2,
	title1 = '@RANBuildDetailListDayLimitTitle',
	title2 = '@RANBuildDetailListMaxLimitTitle',
},
["RANScienceMainPage"] ={
    name = "RANScienceMainPage",
	itemAmount = 2,
	title1 = '@RANScienceMainPageTabTitle1',
	title2 = '@RANScienceMainPageTabTitle2',
},
["RANScienceTreePage"] ={
    name = "RANScienceTreePage",
	itemAmount = 2,
	title1 = '@RANScienceDevelop',
	title2 = '@RANScienceMilitary',
},
["RANationalWarehouseMainPage"] ={
    name = "RANationalWarehouseMainPage",
	itemAmount = 2,
	title1 = '@NS_WarehouseResTitle',
	title2 = '@NS_WarehouseShopTitle',
	aniIndex = 2,
},
["RANationalSpacecraftPage"] ={
    name = "RANationalSpacecraftPage",
	itemAmount = 2,
	title1 = '@NS_SpaceshipModifiedTag',
	title2 = '@NS_SpaceshipStayTurnTag',
	aniIndex = 2,
},
["RAActivitySeaTreasureRewardPopUp"] ={
    name = "RAActivitySeaTreasureRewardPopUp",
	itemAmount = 2,
	title1 = '@Act299Lang5',
	title2 = '@Act299Lang6',
	aniIndex = 2,
},
["RAActivitySeaTreasurePreviewPopUp"] ={
    name = "RAActivitySeaTreasurePreviewPopUp",
	itemAmount = 2,
	title1 = '@Act299Lang5',
	title2 = '@Act299Lang6',
	aniIndex = 2,
},
["RANationWarPage"] ={
    name = "RANationWarPage",
	itemAmount = 2,
	title1 = '@JoinAttack',
	title2 = '@JoinDefense',
	aniIndex = 2,
},
['RAMobaWarBattleRewardPage'] ={
	name = 'RAMobaWarBattleRewardPage',
	itemAmount = 5,
	title1 = '@DyzzLevelName1',
	title2 = '@DyzzLevelName2',
	title3 = '@DyzzLevelName3',
	title4 = '@DyzzLevelName4',
	title5 = '@DyzzLevelName5',
	aniIndex = 5,
},
['RAMobaWarTroopsInfoPage'] ={
	name = 'RAMobaWarTroopsInfoPage',
	itemAmount = 2,
	title1 = '@DyzzSoldierTitle',
	title2 = '@DyzzHeroTitle',
	aniIndex = 2,
},
['RASuperVIPPage'] ={
	name = 'RASuperVIPPage',
	itemAmount = 2,
	title1 = '@SuperVIPActiveLang5',
	title2 = '@SuperVIPActiveLang6',
	aniIndex = 2,
},
['RAStarWarHospitalPage']={
	name = 'RAStarWarHospitalPage',
	itemAmount = 2,
	title1 = '@SwLang1',
	title2 = '@SwLang2',
	aniIndex = 2,
},
['RAActivityShareGloryPage']={
	name = 'RAActivityShareGloryPage',
	itemAmount = 2,
	title1 = '@ShareGloryLang2',
	title2 = '@ShareGloryLang3',
	aniIndex = 2,
},
['RAActivityShareGloryRewardPopUp'] = {
	name = 'RAActivityShareGloryRewardPopUp',
	itemAmount = 3,
	title1 = '@ShareGloryLang23',
	title2 = '@ShareGloryLang25',
	title3 = '@ShareGloryLang38',
	aniIndex = 3,
},
['RAActivityMidAutumnPage']={
	name = 'RAActivityMidAutumnPage',
	itemAmount = 4,
	title1 = '@activity144Title1',
	title2 = '@activity144Title2',
	title3 = '@activity144Title3',
	title4 = '@activity144Title4',
	aniIndex = 4,
},
['RACrossServerGatherPage']={
	name = 'RACrossServerGatherPage',
	itemAmount = 2,
	title1 = '@CrossLang129',
	title2 = '@CrossLang130',
	aniIndex = 2,
},
['RAActivityHonourHeroReturnToFactoryPage']={
	name = 'RAActivityHonourHeroReturnToFactoryPage',
	itemAmount = 2,
	title1 = '@Act309TabTitle1',
	title2 = '@Act309TabTitle2',
	aniIndex = 2,
},
['RAActivityItemRecyclePage']={
	name = 'RAActivityItemRecyclePage',
	itemAmount = 2,
	title1 = '@Act311TableTitle2',
	title2 = '@Act311TableTitle1',
	aniIndex = 2,
},
['RAWorldYQZZBuildngInfoPopUp']={
	name = 'RAWorldYQZZBuildngInfoPopUp',
	itemAmount = 2,
	title1 = '@YQZZLang1',
	title2 = '@YQZZLang2',
	aniIndex = 2,
},
['RAWorldXHJZBuildngInfoPopUp']={
	name = 'RAWorldXHJZBuildngInfoPopUp',
	itemAmount = 2,
	title1 = '@YQZZLang1',
	title2 = '@YQZZLang2',
	aniIndex = 2,
},

['RAWorldFGYLBuildngInfoPopUp']={
	name = 'RAWorldFGYLBuildngInfoPopUp',
	itemAmount = 2,
	title1 = '@FGYLTabBuilding1',
	title2 = '@FGYLTabBuilding2',
	aniIndex = 2,
},
['RAActivityTimeLoverPage'] ={
	name = 'RAActivityTimeLoverPage',
	itemAmount = 2,
	title1 = '@Act100_Tab_1',
	title2 = '@Act100_Tab_2',
},
['RAActivityHeroBackExchangePage'] ={
	name = 'RAActivityHeroBackExchangePage',
	itemAmount = 2,
	title1 = '@Act91_Tab_1',
	title2 = '@Act91_Tab_2',
},
['RAActivityNewYearLotteryPage'] ={
	name = 'RAActivityNewYearLotteryPage',
	itemAmount = 2,
	title1 = '@Act315_Tab_1',
	title2 = '@Act315_Tab_2',
},
['RAActivitySpaceMechaPersonalPopUp'] ={
	name = 'RAActivitySpaceMechaPersonalPopUp',
	itemAmount = 2,
	title1 = '@Act316_Person_Tab_1',
	title2 = '@Act316_Person_Tab_2',
},
['RASuperSoldierEnergyAttriPopUp'] ={
	name = 'RASuperSoldierEnergyAttriPopUp',
	itemAmount = 2,
	title1 = '@MechaLang28',
	title2 = '@MechaLang24',
},
['RASuperSoldierPreviewEffectPopUp'] ={
	name = 'RASuperSoldierPreviewEffectPopUp',
	itemAmount = 2,
	title1 = '@MechaLang40',
	title2 = '@MechaLang41',
},
['RASpaceMechaBuildMainDetailPage'] ={
	name = 'RASpaceMechaBuildMainDetailPage',
	itemAmount = 2,
	title1 = '@SP_Lang1',
	title2 = '@SP_Lang2',
},
['RASpaceMechaBuildSlaveDetailPage'] ={
	name = 'RASpaceMechaBuildSlaveDetailPage',
	itemAmount = 2,
	title1 = '@SP_Lang1',
	title2 = '@SP_Lang2',
},
['RASpaceMechaBuildHoldDetailPage'] ={
	name = 'RASpaceMechaBuildHoldDetailPage',
	itemAmount = 2,
	title1 = '@SP_Lang3',
	title2 = '@SP_Lang4',
},
['RASuperSoldierEnergyPage'] ={
	name = 'RASuperSoldierEnergyPage',
	itemAmount = 2,
	title1 = '@MechaLang29',
	title2 = '@MechaLang30',
},
['RAGlorySeasonRankPopUp'] ={
	name = 'RAGlorySeasonRankPopUp',
	itemAmount = 2,
	title1 = '@GlorySeasonRank',
	title2 = '@GlorySeasonRankReward',
},
['RAActivityWorldHonorPage'] ={
	name = 'RAActivityWorldHonorPage',
	itemAmount = 2,
	title1 = '@ActT321Title1',
	title2 = '@ActT321Title2',
},
['RAActivityWorldHonorBuyPopUp'] ={
	name = 'RAActivityWorldHonorBuyPopUp',
	itemAmount = 2,
	title1 = '@ActT321Title1',
	title2 = '@ActT321Title2',
},
['RAActivityPindanRecordPopUp'] ={
	name = 'RAActivityPindanRecordPopUp',
	itemAmount = 3,
	title1 = '@Act324Lang9',
	title2 = '@Act324Lang10',
	title3 = '@Act324Lang11',
},
['RAShareCoordPersonalPopUp'] ={
	name = 'RAShareCoordPersonalPopUp',
	itemAmount = 3,
	title1 = '@PersonalList',
	title2 = '@FriendsList',
	title3 = '@UnionList',
},
['RAMailListPage'] ={
	name = 'RAMailListPage',
	itemAmount = 2,
	title1 = '@BattleReport',
	title2 = '@InvestigationReport',
},
['RAActivitySplitServerRankPopUp'] ={
	name = 'RAActivitySplitServerRankPopUp',
	itemAmount = 2,
},
['RAActivitySplitServerNormalSignPopUp'] ={
	name = 'RAActivitySplitServerNormalSignPopUp',
	itemAmount = 2,
	title1 = '@Act325Lang14',
	title2 = '@Act325Lang15',
},
['RAActivitySplitServerManagerSignPopUp'] ={
	name = 'RAActivitySplitServerManagerSignPopUp',
	itemAmount = 3,
	title1 = '@Act325Lang16',
	title2 = '@Act325Lang14',
	title3 = '@Act325Lang15',
},
['RAActivityLGGLotteryRecordPopUp'] ={
	name = 'RAActivityLGGLotteryRecordPopUp',
	itemAmount = 2,
	title1 = '@Act327RecordTabTitle1',
	title2 = '@Act327RecordTabTitle2',
},
['RAActivitySplitServerInvitePage'] ={
	name = 'RAActivitySplitServerInvitePage',
	itemAmount = 2,
	title1 = '@Act325Lang20',
	title2 = '@Act325Lang21',
},
['RAActivitySplitServerMoveListPopUp'] ={
	name = 'RAActivitySplitServerMoveListPopUp',
	itemAmount = 2,
	title1 = '@Act325Lang22',
	title2 = '@Act325Lang23',
},
['RASkinPage2'] ={
	name = 'RASkinPage2',
	itemAmount = 2,
	title1 = '@RASkinLang1',
	title2 = '@RASkinLang2',
},
['RASkinPage3'] ={
	name = 'RASkinPage3',
	itemAmount = 3,
	title1 = '@RASkinLang1',
	title2 = '@RASkinLang2',
	title3 = '@RASkinLang20',
},
['RASkinPage4'] ={
	name = 'RASkinPage4',
	itemAmount = 4,
	title1 = '@RASkinLang1',
	title2 = '@RASkinLang2',
	title3 = '@RASkinLang20',
	title4 = '@RASkinLang3',
},
['RASkinMythTab'] ={
	name = 'RASkinMythTab',
	itemAmount = 2,
	title1 = '@RASkinLang4',
	title2 = '@RASkinLang5',
},
['RAActivitySoldierExchangePage'] ={
	name = 'RAActivitySoldierExchangePage',
	itemAmount = 2,
	title1 = '@Act328Lang1',
	title2 = '@Act328Lang2',
},
['RAActivityBackSoldierExchangePage'] ={
	name = 'RAActivityBackSoldierExchangePage',
	itemAmount = 2,
	title1 = '@Act328Lang1',
	title2 = '@Act328Lang2',
},
['RA389ActivitySoldierExchangePage'] ={
	name = 'RA389ActivitySoldierExchangePage',
	itemAmount = 2,
	title1 = '@Act389Lang1',
	title2 = '@Act389Lang2',
},
['RAMailFightHeroPopUp'] ={
	name = 'RAMailFightHeroPopUp',
	itemAmount = 2,
	title1 = '@MailSOHeroTitle1',
	title2 = '@MailSOHeroTitle2',
},
['RAMedalFactoryFormationPage'] ={
	name = 'RAMedalFactoryFormationPage',
	itemAmount = 2,
	title1 = '@MedalFactroyLang14',
	title2 = '@MedalFactroyLang16',
},
['RAPointSprintMainPage'] ={
	name = 'RAPointSprintMainPage',
	itemAmount = 2,
	title1 = '@RAAct345Lang1',
	title2 = '@RAAct345Lang2',
},
['RAActivityStarExploreRecordPopUp'] = {
	name = 'RAActivityStarExploreRecordPopUp',
	itemAmount = 2,
	title1 = '@RAActivity347Lang9',
	title2 = '@RAActivity347Lang10',
},
['RAActivitySupplyCrateRewardPopUp'] = {
	name = 'RAActivitySupplyCrateRewardPopUp',
	itemAmount = 2,
	title1 = '@RAActivity348Lang9',
	title2 = '@RAActivity348Lang10',
},
['RAHero3SSoulPreviewPopUp'] ={
	name = 'RAHero3SSoulPreviewPopUp',
	itemAmount = 3,
	title1 = '@RAHeroSoulLang15',
	title2 = '@RAHeroSoulLang16',
	title3 = '@RAHeroSoulLang17',
},
['RAActivityLotteryTicketInvitePopUp'] ={
	name = 'RAActivityLotteryTicketInvitePopUp',
	itemAmount = 3,
	title1 = '@RAActivity353Lang7',
	title2 = '@RAActivity353Lang8',
	title3 = '@RAActivity353Lang9',
},
['RAActivityReturnUpgradeShopPopUp'] ={
	name = 'RAActivityReturnUpgradeShopPopUp',
	itemAmount = 4,
	title1 = '@RAAct346ShopTabTitle1',
	title2 = '@RAAct346ShopTabTitle2',
	title3 = '@RAAct346ShopTabTitle3',
	title4 = '@RAAct346ShopTabTitle4',
},
['RAActivityMidLevelDevPage'] ={
	name = 'RAActivityMidLevelDevPage',
	tabCCBName = "mCommonTab2CCB",
	itemAmount = 2,
	title1 = '@Act349_tab1',
	title2 = '@Act349_tab2',
},
['RAActivityAnniversarySixPage'] ={
	name = 'RAActivityAnniversarySixPage',
	cellCCBName = 'RAActivity354NodeTabV5.ccbi',
	itemAmount = 6,
	title1 = '@Act354_tab1',
	title2 = '@Act354_tab2',
	title3 = '@Act354_tab3',
	title4 = '@Act354_tab4',
	title5 = '@Act354_tab5',
	title6 = '@Act354_tab6',
},
['RASuperSoldierListPage'] ={
	name = 'RASuperSoldierListPage',
	tabCCBName = "mCommonTab2CCB",
	itemAmount = 2,
	title1 = '@MechaHuanxingLang1',
	title2 = '@MechaHuanxingLang2',
},
['RAManhattanFoundationPage'] ={
	name = 'RAManhattanFoundationPage',
	itemAmount = 2,
	title1 = '@ManhattanBase_LevelUp_Title',
	title2 = '@ManhattanBase_StageUp_Title',
},
['RAManhattanStrengthenPage'] ={
	name = 'RAManhattanStrengthenPage',
	itemAmount = 2,
	title1 = '@ManhattanSW_LevelUp_Title',
	title2 = '@ManhattanSW_StageUp_Title',
},
['RAManhattanSWInfoPopUp'] ={
	name = 'RAManhattanSWInfoPopUp',
	itemAmount = 2,
	title1 = '@ManhattanSW_Battle_Attr_Title',
	title2 = '@ManhattanSW_Battle_AllSW_Title',
},
['RAManhattanWorldEffPopUp'] ={
	name = 'RAManhattanWorldEffPopUp',
	itemAmount = 2,
	title1 = '@ManhattanSW_ShowAppearance_Title1',
	title2 = '@ManhattanSW_ShowAppearance_Title2',
},
['RAManhattanEffListPopUp'] ={
	name = 'RAManhattanEffListPopUp',
	itemAmount = 2,
	title1 = '@ManhattanBase_ShowAttr_Button1',
	title2 = '@ManhattanBase_ShowAttr_Button2',
},
['RAManhattanOverviewEffPopUp'] ={
	name = 'RAManhattanOverviewEffPopUp',
	itemAmount = 2,
	title1 = '@ManhattanSW_ShowAttr_Button_Now',
	title2 = '@ManhattanSW_ShowAttr_Button_Ult',
},
['RAActivityShootingPracticeRankPopUp'] ={
	name = 'RAActivityShootingPracticeRankPopUp',
	itemAmount = 2,
	title1 = '@Act317RankTitle1',
	title2 = '@Act317RankTitle2',
},
['RAActivitySubmarineBattleRankPopUp'] ={
	name = 'RAActivitySubmarineBattleRankPopUp',
	itemAmount = 3,
	title1 = '@Act317RankTitle1',
	title2 = '@Act317RankTitle2',
	title3 = '@Act364RankSheet3',
},
['RAActivityStarInvestPage'] ={
	name = 'RAActivityStarInvestPage',
	itemAmount = 2,
	title1 = '@RAAct358_tab1',
	title2 = '@RAAct358_tab2',
},
['RAActivityEscortPage'] ={
	name = 'RAActivityEscortPage',
	itemAmount = 3,
	title1 = '@RAAct375_tab1',
	title2 = '@RAAct375_tab2',
	title3 = '@RAAct375_tab3',
},
['RAActivityEscortHistoryPopUp'] ={
	name = 'RAActivityEscortHistoryPopUp',
	itemAmount = 2,
	title1 = '@RAAct375_hisTab1',
	title2 = '@RAAct375_hisTab2',
},

['RAActivityEscortFormationPage'] ={
	name = 'RAActivityEscortFormationPage',
	itemAmount = 2,
	title1 = '@RAAct375_FormationTab1',
	title2 = '@RAAct375_FormationTab2',
},

['RAActivityEscortPreviewPopUp'] ={
	name = 'RAActivityEscortPreviewPopUp',
	itemAmount = 2,
	title1 = '@Act375Lang24',
	title2 = '@Act375Lang25',
},

['RAActivityALRushMainPage'] ={
	name = 'RAActivityALRushMainPage',
	itemAmount = 2,
	title1 = '@Act385Label3',
	title2 = '@Act385Label4',
},

['RAActivityStarInvestDetectorDescPopUp'] ={
	name = 'RAActivityStarInvestDetectorDescPopUp',
	itemAmount = 2,
	title1 = '@RAAct358_DescTab1',
	title2 = '@RAAct358_DescTab2',
},

['RAActivityPlantWeaponDetailPopUp'] = {
	name = 'RAActivityPlantWeaponDetailPopUp',
	itemAmount = 2,
	title1 = '@RAActivity355Lang4',
	title2 = '@RAActivity355Lang5',
},

['RAActivityGuildBackPage'] = {
	name = 'RAActivityGuildBackPage',
	itemAmount = 2,
	title1 = '@RAActivity359TabTitle1',
	title2 = '@RAActivity359TabTitle2',
},

['RAPlantSoldierEffectTipsPopUp'] = {
	name = 'RAPlantSoldierEffectTipsPopUp',
	itemAmount = 2,
	title1 = '@RASkinLang16',
	title2 = '@RASkinLang17',
},
['RAActivityMJXBTaskPopUp'] = {
	name = 'RAActivityMJXBTaskPopUp',
	itemAmount = 2,
	title1 = '@DailyTask',
	title2 = '@WeeklyTask',
},
['RASeasonXHJZBattleInfoPage'] = {
	name = 'RASeasonXHJZBattleInfoPage',
	itemAmount = 2,
	title1 = '@Season_XHJZ_TabBattleRank',
	title2 = '@Season_XHJZ_TabBattleInfo',
},
['RASeasonXHJZRecordPopUp'] = {
	name = 'RASeasonXHJZRecordPopUp',
	itemAmount = 2,
	title1 = '@Season_XHJZ_QualifierGame',
	title2 = '@Season_XHJZ_RankingGame',
},
['RASeasonXQHXBattleInfoPage'] = {
	name = 'RASeasonXQHXBattleInfoPage',
	itemAmount = 2,
	title1 = '@Season_XQHX_TabBattleRank',
	title2 = '@Season_XQHX_TabBattleInfo',
},
['RASeasonXQHXRecordPopUp'] = {
	name = 'RASeasonXQHXRecordPopUp',
	itemAmount = 2,
	title1 = '@Season_XQHX_QualifierGame',
	title2 = '@Season_XQHX_RankingGame',
},
['RAMechaCoreMainPage'] = {
	name = 'RAMechaCoreMainPage',
	itemAmount = 2,
	title1 = '@RAMechaCoreLang1',
	title2 = '@RAMechaCoreLang2',
},
['RAMechaCoreOverviewEffPopUp'] = {
	name = 'RAMechaCoreOverviewEffPopUp',
	itemAmount = 2,
	title1 = '@RAMechaCoreLang21',
	title2 = '@RAMechaCoreLang22',
},
['RAActivityCompetitonPartyRecordPopUp'] = {
	name = 'RAActivityCompetitonPartyRecordPopUp',
	itemAmount = 2,
	title1 = '@Act371_txt0002',
	title2 = '@Act371_txt0003',
},
['RAObeliskNewRankPopUp'] ={
	name = 'RAObeliskNewRankPopUp',
	-- cellCCBName = 'RAzzPopUpCommonTab2V3.ccbi',
	itemAmount = 2,
	title1 = '@ObeliskNewRankTitle1',
	title2 = '@ObeliskNewRankTitle2',
},
['RAActivityGuildBossRewardPopUp'] ={
	name = 'RAActivityGuildBossRewardPopUp',
	-- cellCCBName = 'RAzzPopUpCommonTab2V3.ccbi',
	itemAmount = 2,
	title1 = '@RAAct374Lang12',
	title2 = '@RAAct374Lang13',
},
['RACityGainPage'] ={
	name = 'RACityGainPage',
	itemAmount = 2,
	title1 = '@BuffPageName1',
	title2 = '@BuffPageName2',
},

['RA3SSkillTips'] ={
	name = 'RA3SSkillTips',
	itemAmount = 2,
	title1 = '@RA3SSkillTipsTitle1',
	title2 = '@RA3SSkillTipsTitle2',
},
['RAActivityHotBloodWarTaskPopUp'] ={
	name = 'RAActivityHotBloodWarTaskPopUp',
	itemAmount = 2,
	title1 = '@Act378TaskTab1',
	title2 = '@Act378TaskTab2',
},
['RAHomeItemListPage'] = {
	name = 'RAHomeItemListPage',
	itemAmount = 3,
	title1 = '@RAHomeLang5',
	title2 = '@RAHomeLang6',
	title3 = '@RAHomeLang44',
},
['RAHomeRankPage'] = {
	name = 'RAHomeRankPage',
	itemAmount = 2,
	title1 = '@RAHomeLang21',
	title2 = '@RAHomeLang22',
},
['RAActivityAnn7PartyPreviewPopUp'] = {
	name = 'RAActivityAnn7PartyPreviewPopUp',
	itemAmount = 2,
	title1 = '@Act384PartyLabel3',
	title2 = '@Act384PartyLabel4',
},
['RAAllianceActDungeonInfoPopUp'] = {
	name = 'RAAllianceActDungeonInfoPopUp',
	itemAmount = 4,
	cellCCBName = 'TiberiumMainPageTitle.ccbi',
	title1 = '@TiberiumMainPageTitle',
	title2 = '@CyborgWar',
	title3 = '@XQHXTitle',
	title4 = '@CrossServerTitle',
},

['RAActivityAnn7PartyRecordDetailPopUp'] ={
	name = 'RAActivityAnn7PartyRecordDetailPopUp',
	itemAmount = 3,
	title1 = '@Act384_0031',
	title2 = '@Act384_0032',
	title3 = '@Act384_0033',
},
['RAPersonalProcessInfoPage'] = {
	name = 'RAPersonalProcessInfoPage',
	itemAmount = 2,
	title1 = '@milestoneDes_004',
	title2 = '@milestoneDes_005',
},
['RAHeroMilitaryPage'] = {
	name = 'RAHeroMilitaryPage',
	itemAmount = 6,
	title1 = '@AllHeroFilter',
	title2 = '@TankHeroFilter',
	title3 = '@InfantryHeroFilter',
	title4 = '@AirplaneHeroFilter',
	title5 = '@ChariotHeroFilter',
	title6 = '@UniversalHeroFilter',
},
['RAActivityFindStoreRewardPopUp'] = {
	name = 'RAActivityFindStoreRewardPopUp',
	itemAmount = 2,
	title1 = '@Act386LangTab1',
	title2 = '@Act386LangTab2',
},
['RAActivityFindStorePylonListPopUp'] = {
	name = 'RAActivityFindStorePylonListPopUp',
	itemAmount = 2,
	title1 = '@Act386LangTab3',
	title2 = '@Act386LangTab4',
},
['RAActivityArmourImmortDecPopUp'] = {
	name = 'RAActivityArmourImmortDecPopUp',
	itemAmount = 2,
	title1 = '@RAAct388Lang3',
	title2 = '@RAAct388Lang4',
},
['RAOBRoomListPage'] = {
	name = 'RAOBRoomListPage',
	cellCCBName = 'RAOBEntranceTabNodeV3.ccbi',
	itemAmount = 2,
	title1 = '@schedule_title_1',
	title2 = '@schedule_title_2',
},
['RAArmourImmort_RefactorHelpPopUp'] = {
	name = 'RAArmourImmort_RefactorHelpPopUp',
	itemAmount = 2,
	title1 = '@EquipImmortal_TabRuleRandom1',
	title2 = '@EquipImmortal_TabRuleRandom2',
},
['RAArmourImmortMainPage'] = {
	name = 'RAArmourImmortMainPage',
	itemAmount = 2,
	title1 = '@EquipImmortal_Tab1',
	-- title2 = '@EquipImmortal_Tab2',
	title2 = '@EquipImmortal_Tab3',
}
}
return page_tabs_conf


