local player_item_conf = {
[1000] ={
	id = 1000,
	name = '@diamondName',
	item_color = 5,
	ResourceFieldicon = 'V3CommonUI_Icon_Diamonds_02.png',
	icon = 'V3CommonUI_Icon_Diamonds_01.png',
	middleIcon = 'V3CommonUI_Icon_Diamonds_02.png',
	bigIcon = 'V3CommonUI_Icon_Diamonds_03.png',
	des = '@diamondDes',
},
[1001] ={
	id = 1001,
	name = '@crystalName',
	item_color = 4,
	ResourceFieldicon = 'V3CommonUI_Icon_Crystal_02.png',
	icon = 'V3CommonUI_Icon_Crystal_01.png',
	middleIcon = 'V3CommonUI_Icon_Crystal_02.png',
	bigIcon = 'V3CommonUI_Icon_Crystal_03.png',
	des = '@crystalDes',
	bannerIcon = 'Banner_CystalsIcon.png'
},
[1002] ={
	id = 1002,
	name = '@goldName',
	item_color = 4,
	ResourceFieldicon = 'V3CommonUI_Icon_Gold_01.png',
	icon = 'V3CommonUI_Icon_Gold_01.png',
},
[1003] ={
	id = 1003,
	item_color = 1,
},
[1004] ={
	id = 1004,
	name = '@ExpName',
	item_color = 1,
	ResourceFieldicon = 'Item_QuestIcon_Exp.png',
	icon = 'Item_QuestIcon_Exp.png',
	middleIcon = 'Item_QuestIcon_Exp.png',
	des = '@expDes',
},
[1005] ={
	id = 1005,
	name = '@VipPointName',
	item_color = 4,
	ResourceFieldicon = 'V3CommonUI_Icon_VipPoint_01.png',
	icon = 'V3CommonUI_Icon_VipPoint_01.png',
	des = '@VipPointDes',
},
[1006] ={
	id = 1006,
	item_color = 1,
	des = '@electricDes',
},
[1007] ={
	id = 1007,
	name = '@gold01Name',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_Gold_02.png',
	icon = 'V3CommonUI_Icon_Gold_02.png',
	middleIcon = 'V3CommonUI_Icon_Gold_03.png',
	bigIcon = 'V3CommonUI_Icon_Gold_03.png',
	des = '@GoldDes',
},
[1008] ={
	id = 1008,
	name = '@oilName',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_Petroleum_02.png',
	icon = 'V3CommonUI_Icon_Petroleum_02.png',
	middleIcon = 'V3CommonUI_Icon_Petroleum_03.png',
	bigIcon = 'V3CommonUI_Icon_Petroleum_03.png',
	des = '@oilDes',
},
[1009] ={
	id = 1009,
	name = '@uraniumName',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_Uranium_02.png',
	icon = 'V3CommonUI_Icon_Uranium_02.png',
	middleIcon = 'V3CommonUI_Icon_Uranium_03.png',
	bigIcon = 'V3CommonUI_Icon_Uranium_03.png',
	des = '@xitulDes',
},
[1010] ={
	id = 1010,
	name = '@metalName',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_Steel_02.png',
	icon = 'V3CommonUI_Icon_Steel_02.png',
	middleIcon = 'V3CommonUI_Icon_Steel_03.png',
	bigIcon = 'V3CommonUI_Icon_Steel_03.png',
	des = '@metalDes',
},
[1011] ={
	id = 1011,
	name = '@Stamina',
	item_color = 3,
	ResourceFieldicon = 'Item_Energy.png',
	icon = 'Item_Energy.png',
	middleIcon = 'Item_Energy.png',
	bigIcon = 'Item_Energy.png',
	des = '@spiritDes',
},
[1012] ={
	id = 1012,
	item_color = 1,
},
[1013] ={
	id = 1013,
	item_color = 1,
},
[1014] ={
	id = 1014,
	name = '@CurrencyName_1014',
	item_color = 1,
	ResourceFieldicon = 'V3Alliance_Icon_Donation_01.png',
	icon = 'V3Alliance_Icon_Donation_01.png',
	bigIcon = 'V3Alliance_Icon_Donation_011.png',
	des = '@CurrencyDes_1014',
},
[1015] ={
	id = 1015,
	item_color = 1,
},
[1017] ={
	id = 1017,
	name = '@CurrencyName_1017',
	item_color = 1,
	ResourceFieldicon = 'V3Alliance_Icon_Donation_02.png',
	icon = 'V3Alliance_Icon_Donation_02.png',
	bigIcon = 'V3Alliance_Icon_Donation_022.png',
	des = '@CurrencyDes_1017',
},
[1107] ={
	id = 1107,
	name = '@gold01Name',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_Gold_01.png',
	icon = 'V3CommonUI_Icon_Gold_01.png',
	middleIcon = 'V3CommonUI_Icon_Gold_03.png',
	bigIcon = 'V3CommonUI_Icon_Gold_03.png',
	des = '@GoldDes',
},
[1108] ={
	id = 1108,
	name = '@oilName',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_Petroleum_01.png',
	icon = 'V3CommonUI_Icon_Petroleum_01.png',
	middleIcon = 'V3CommonUI_Icon_Petroleum_03.png',
	bigIcon = 'V3CommonUI_Icon_Petroleum_03.png',
	des = '@oilDes',
},
[1109] ={
	id = 1109,
	name = '@uraniumName',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_Uranium_01.png',
	icon = 'V3CommonUI_Icon_Uranium_01.png',
	middleIcon = 'V3CommonUI_Icon_Uranium_03.png',
	bigIcon = 'V3CommonUI_Icon_Uranium_03.png',
	des = '@xitulDes',
},
[1110] ={
	id = 1110,
	name = '@metalName',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_Steel_01.png',
	icon = 'V3CommonUI_Icon_Steel_01.png',
	middleIcon = 'V3CommonUI_Icon_Steel_03.png',
	bigIcon = 'V3CommonUI_Icon_Steel_03.png',
	des = '@metalDes',
},
[1111] ={
	id = 1111,
	name = '@EquipFuel',
	item_color = 1,
	ResourceFieldicon = 'Item_Material_01_01.png',
	icon = 'Item_Material_01_01.png',
	middleIcon = 'Item_Material_01_02.png',
	bigIcon = 'Item_Material_01_03.png',
	des = '@EquipFuelDes',
},
[1018] ={
	id = 1018,
	name = '@RankName',
	item_color = 1,
	ResourceFieldicon = 'Item_MilitaryRanks.png',
	icon = 'Item_MilitaryRanks.png',
	middleIcon = 'Item_MilitaryRanks.png',
	bigIcon = 'Item_MilitaryRanks.png',
	des = '@RankDes',
},
[1019] ={
	id = 1019,
	name = '@MilitaryMoneyName',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_MILPoint_02.png',
	icon = 'V3CommonUI_Icon_MILPoint_01.png',
	middleIcon = 'V3CommonUI_Icon_MILPoint_02.png',
	bigIcon = 'V3CommonUI_Icon_MILPoint_03.png',
	des = '@MilitaryMoneyDes',
},
[1020] ={
	id = 1020,
	name = '@TiberiumResource',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_Tiberium_01.png',
	icon = 'V3CommonUI_Icon_Tiberium_01.png',
	middleIcon = 'V3CommonUI_Icon_Tiberium_03.png',
	bigIcon = 'V3CommonUI_Icon_Tiberium_03.png',
},
[1021] ={
	id = 1021,
	name = '@CyborgMoney',
	item_color = 1,
	ResourceFieldicon = 'Item_Cyborg_Score.png',
	icon = 'Item_Cyborg_Score.png',
	middleIcon = 'Item_Cyborg_Score.png',
	bigIcon = 'Item_Cyborg_Score.png',
	des = '@CyborgMoneyDes',
},
[1026] ={
	id = 1026,
	name = '@shopFriendPointName',
	item_color = 1,
	ResourceFieldicon = 'Item_TravelShop_FriendlyPoint.png',
	icon = 'Item_TravelShop_FriendlyPoint.png',
	middleIcon = 'Item_TravelShop_FriendlyPoint.png',
	bigIcon = 'Item_TravelShop_FriendlyPoint.png',
	des = '@shopFriendPointDesc',
},
[1027] ={
	id = 1027,
	name = '@dyzzyunjing1',
	item_color = 1,
	ResourceFieldicon = 'V15v5_BlackMerchant_Icon_01.png',
	icon = 'V15v5_BlackMerchant_Icon_01.png',
	middleIcon = 'V15v5_BlackMerchant_Icon_01.png',
	bigIcon = 'V3CommonUI_Icon_Tiberium_03.png',
	des = '@dyzzyunjing2',
},
[1028] ={
	id = 1028,
	name = '@dyzzyunjing3',
	item_color = 1,
	ResourceFieldicon = 'Item_5v5_01.png',
	icon = 'Item_5v5_01.png',
	middleIcon = 'Item_5v5_01.png',
	bigIcon = 'Item_5v5_01.png',
	des = '@dyzzyunjing4',
},
[1029] ={
	id = 1029,
	name = '@CrossLang87',
	item_color = 1,
	ResourceFieldicon = 'Item_CrossServer_Strategy_01.png',
	icon = 'Item_CrossServer_Strategy_01.png',
	middleIcon = 'Item_CrossServer_Strategy_01.png',
	bigIcon = 'Item_CrossServer_Strategy_01.png',
	des = '@CrossLang88',
},
[1031] ={
	id = 1031,
	name = '@CrossLang84',
	item_color = 1,
	ResourceFieldicon = 'Item_MilitaryRank_01.png',
	icon = 'Item_MilitaryRank_01.png',
	middleIcon = 'Item_MilitaryRank_01.png',
	bigIcon = 'Item_MilitaryRank_01.png',
	des = '@CrossLang100',
},
[1207] ={
	id = 1207,
	name = '@nationResource01',
	item_color = 1,
	ResourceFieldicon = 'Item_Nation_Res_01.png',
	icon = 'Item_Nation_Res_01.png',
	middleIcon = 'Item_Nation_Res_01.png',
	bigIcon = 'Item_Nation_Res_01.png',
	des = '@nationResourceDes01',
},
[1208] ={
	id = 1208,
	name = '@nationResource02',
	item_color = 1,
	ResourceFieldicon = 'Item_Nation_Res_02.png',
	icon = 'Item_Nation_Res_02.png',
	middleIcon = 'Item_Nation_Res_02.png',
	bigIcon = 'Item_Nation_Res_02.png',
	des = '@nationResourceDes02',
},
[1209] ={
	id = 1209,
	name = '@nationResource03',
	item_color = 1,
	ResourceFieldicon = 'Item_Nation_Res_03.png',
	icon = 'Item_Nation_Res_03.png',
	middleIcon = 'Item_Nation_Res_03.png',
	bigIcon = 'Item_Nation_Res_03.png',
	des = '@nationResourceDes03',
},
[1210] ={
	id = 1210,
	name = '@nationResource04',
	item_color = 1,
	ResourceFieldicon = 'Item_Nation_Res_04.png',
	icon = 'Item_Nation_Res_04.png',
	middleIcon = 'Item_Nation_Res_04.png',
	bigIcon = 'Item_Nation_Res_04.png',
	des = '@nationResourceDes04',
},
[1211] ={
	id = 1211,
	name = '@TiberiumResource',
	item_color = 1,
	ResourceFieldicon = 'V3CommonUI_Icon_Tiberium_01.png',
	icon = 'V3CommonUI_Icon_Tiberium_01.png',
	middleIcon = 'V3CommonUI_Icon_Tiberium_03.png',
	bigIcon = 'V3CommonUI_Icon_Tiberium_03.png',
}
}
return player_item_conf
