local question_conf = {
[1] ={
	id = 1,
	answer = 'Question1',
},
[2] ={
	id = 2,
	answer = 'Question2',
},
[3] ={
	id = 3,
	answer = 'Question3',
},
[4] ={
	id = 4,
	name = '@QuestionName4',
	keyWordsID = '提升战力_升战力_提升战斗力',
	answer = 'Question4',
	associatedID = '22_25_41_8_100',
	des = 'QuestionName4',
	infor = 'StrategyInfor4',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6521571'
},
[5] ={
	id = 5,
	name = '@QuestionName5',
	keyWordsID = '升级建筑工厂_升级工厂_升堡_冲堡',
	answer = 'Question5',
	associatedID = 131,
	des = 'QuestionName5',
	infor = 'StrategyInfor5',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6497956'
},
[6] ={
	id = 6,
	name = '@QuestionName6',
	keyWordsID = '抽英雄_英雄招募_获得英雄',
	answer = 'Question6',
	associatedID = '41_7',
	des = 'QuestionName6',
	infor = 'StrategyInfor6',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6504020'
},
[7] ={
	id = 7,
	name = '@QuestionName7',
	keyWordsID = '芯片_选择芯片',
	answer = 'Question7',
	associatedID = '6_42_43_49_50_51',
	des = 'QuestionName7',
	infor = 'StrategyInfor7',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6539534'
},
[8] ={
	id = 8,
	name = '@QuestionName8',
	keyWordsID = '兵种_兵种选择',
	answer = 'Question8',
	associatedID = '55_56_57_58_59_60_53_54',
	des = 'QuestionName8',
	infor = 'StrategyInfor8',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6518554'
},
[9] ={
	id = 9,
	name = '@QuestionName9',
	keyWordsID = '指挥中心_出征上限_出征部队的数量_出征_部队',
	answer = 'Question9',
	des = 'QuestionName9',
	infor = 'StrategyInfor9',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6530416'
},
[10] ={
	id = 10,
	name = '@QuestionName10',
	keyWordsID = '矿厂',
	answer = 'Question10',
	associatedID = '11_12_13_69',
	des = 'QuestionName10',
	infor = 'StrategyInfor10',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6521617'
},
[11] ={
	id = 11,
	name = '@QuestionName11',
	keyWordsID = '油井',
	answer = 'Question11',
	associatedID = '10_12_13_70',
	des = 'QuestionName11',
	infor = 'StrategyInfor11',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6501411'
},
[12] ={
	id = 12,
	name = '@QuestionName12',
	keyWordsID = '稀土矿',
	answer = 'Question12',
	associatedID = '10_11_13_72',
	des = 'QuestionName12',
	infor = 'StrategyInfor12',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6501407'
},
[13] ={
	id = 13,
	name = '@QuestionName13',
	keyWordsID = '合金工厂',
	answer = 'Question13',
	associatedID = '10_11_12_71',
	des = 'QuestionName13',
	infor = 'StrategyInfor13',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6501411'
},
[14] ={
	id = 14,
	name = '@QuestionName14',
	keyWordsID = '征兵处_征兵',
	answer = 'Question14',
	des = 'QuestionName14',
},
[15] ={
	id = 15,
	name = '@QuestionName15',
	keyWordsID = '资源枢纽_枢纽',
	answer = 'Question15',
	des = 'QuestionName15',
},
[16] ={
	id = 16,
	name = '@QuestionName16',
	keyWordsID = '防空洞',
	answer = 'Question16',
	des = 'QuestionName16',
	infor = 'StrategyInfor16',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6503138'
},
[17] ={
	id = 17,
	name = '@QuestionName17',
	keyWordsID = '仓库',
	answer = 'Question17',
	des = 'QuestionName17',
},
[18] ={
	id = 18,
	name = '@QuestionName18',
	keyWordsID = '空指部',
	answer = 'Question18',
	associatedID = '59_60_132',
	des = 'QuestionName18',
},
[19] ={
	id = 19,
	name = '@QuestionName19',
	keyWordsID = '战车工厂',
	answer = 'Question19',
	associatedID = '53_54_132',
	des = 'QuestionName19',
	infor = 'StrategyInfor19',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513746'
},
[20] ={
	id = 20,
	name = '@QuestionName20',
	keyWordsID = '坦克工厂',
	answer = 'Question20',
	associatedID = '55_56_132',
	des = 'QuestionName20',
	infor = 'StrategyInfor20',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6503538'
},
[21] ={
	id = 21,
	name = '@QuestionName21',
	keyWordsID = '兵营',
	answer = 'Question21',
	associatedID = '57_58_132',
	des = 'QuestionName21',
	infor = 'StrategyInfor21',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513745'
},
[22] ={
	id = 22,
	name = '@QuestionName22',
	keyWordsID = '城防工厂',
	answer = 'Question22',
	associatedID = '61_62_63',
	des = 'QuestionName22',
	infor = 'StrategyInfor22',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6505579'
},
[23] ={
	id = 23,
	name = '@QuestionName23',
	keyWordsID = '围墙_打飞_着火_灭火',
	answer = 'Question23',
	des = 'QuestionName23',
	infor = 'StrategyInfor23',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6505579'
},
[24] ={
	id = 24,
	name = '@QuestionName24',
	keyWordsID = '光棱塔_防御塔',
	answer = 'Question24',
	des = 'QuestionName24',
},
[25] ={
	id = 25,
	name = '@QuestionName25',
	keyWordsID = '科技_作战实验室_实验室',
	answer = 'Question25',
	des = 'QuestionName25',
},
[26] ={
	id = 26,
	name = '@QuestionName26',
	keyWordsID = '特惠_特惠商人',
	answer = 'Question26',
	des = 'QuestionName26',
	infor = 'StrategyInfor26',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6516206'
},
[27] ={
	id = 27,
	name = '@QuestionName27',
	keyWordsID = 'buff_基地增益',
	answer = 'Question27',
	associatedID = '47_66',
	des = 'QuestionName27',
},
[28] ={
	id = 28,
	name = '@QuestionName28',
	keyWordsID = '雷达',
	answer = 'Question28',
	associatedID = 95,
	des = 'QuestionName28',
	infor = 'StrategyInfor28',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6534956'
},
[29] ={
	id = 29,
	name = '@QuestionName29',
	keyWordsID = '杀敌榜_战力榜_联盟榜_排行榜',
	answer = 'Question29',
	des = 'QuestionName29',
},
[30] ={
	id = 30,
	name = '@QuestionName30',
	keyWordsID = '援军上限_联盟大厦',
	answer = 'Question30',
	des = 'QuestionName30',
	infor = 'StrategyInfor30',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6506566'
},
[31] ={
	id = 31,
	name = '@QuestionName31',
	keyWordsID = '集结上限_集结指挥部',
	answer = 'Question31',
	associatedID = 96,
	des = 'QuestionName31',
	infor = 'StrategyInfor31',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348520'
},
[32] ={
	id = 32,
	name = '@QuestionName32',
	keyWordsID = '大使馆_好友_黑名单_拉黑',
	answer = 'Question32',
	des = 'QuestionName32',
},
[33] ={
	id = 33,
	name = '@QuestionName33',
	keyWordsID = '贸易中心',
	answer = 'Question33',
	des = 'QuestionName33',
	infor = 'StrategyInfor33',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348520'
},
[34] ={
	id = 34,
	name = '@QuestionName34',
	keyWordsID = '军需处',
	answer = 'Question34',
	des = 'QuestionName34',
},
[35] ={
	id = 35,
	name = '@QuestionName35',
	keyWordsID = '超时空转换器',
	answer = 'Question35',
	des = 'QuestionName35',
},
[36] ={
	id = 36,
	name = '@QuestionName36',
	keyWordsID = '医馆_医院_维修中心',
	answer = 'Question36',
	des = 'QuestionName36',
	infor = 'StrategyInfor36',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6515649'
},
[37] ={
	id = 37,
	name = '@QuestionName37',
	keyWordsID = '联盟堡垒_联盟基地',
	answer = 'Question37',
	associatedID = '38_39_40',
	des = 'QuestionName37',
	infor = 'StrategyInfor37',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348520'
},
[38] ={
	id = 38,
	name = '@QuestionName38',
	keyWordsID = '联盟矿_联盟超级矿',
	answer = 'Question38',
	des = 'QuestionName38',
	infor = 'StrategyInfor38',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348520'
},
[39] ={
	id = 39,
	name = '@QuestionName39',
	keyWordsID = '联盟守备塔',
	answer = 'Question39',
	des = 'QuestionName39',
	infor = 'StrategyInfor39',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348520'
},
[40] ={
	id = 40,
	name = '@QuestionName40',
	keyWordsID = '联盟仓库',
	answer = 'Question40',
	des = 'QuestionName40',
	infor = 'StrategyInfor40',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348520'
},
[41] ={
	id = 41,
	name = '@QuestionName41',
	keyWordsID = '英雄_选择英雄',
	answer = 'Question41',
	associatedID = '44_45_46',
	des = 'QuestionName41',
	infor = 'StrategyInfor41',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513714'
},
[42] ={
	id = 42,
	name = '@QuestionName42',
	keyWordsID = '英雄升级_升级英雄',
	answer = 'Question42',
	associatedID = '43_6',
	des = 'QuestionName42',
	infor = 'StrategyInfor42',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348519'
},
[43] ={
	id = 43,
	name = '@QuestionName43',
	keyWordsID = '升星_英雄升星',
	answer = 'Question43',
	associatedID = '42_6_138',
	des = 'QuestionName43',
	infor = 'StrategyInfor43',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348519'
},
[44] ={
	id = 44,
	name = '@QuestionName44',
	keyWordsID = '大黄蜂_加里森_罗曼诺夫_阿帕奇_公爵_邦德_铁皮_戴安娜_军事英雄',
	answer = 'Question44',
	associatedID = '45_46',
	des = 'QuestionName44',
	infor = 'StrategyInfor44',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513714'
},
[45] ={
	id = 45,
	name = '@QuestionName45',
	keyWordsID = '伊娃_娜迦_居里_特斯拉_雨果_爱丽丝_索菲亚_伊丽莎白_工业英雄',
	answer = 'Question45',
	associatedID = '44_46',
	des = 'QuestionName45',
	infor = 'StrategyInfor45',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513714'
},
[46] ={
	id = 46,
	name = '@QuestionName46',
	keyWordsID = '维多利亚_凌梁_安琪拉_劳拉_马库斯_布兰妮_娜塔莎_兰博_泰山_特蕾莎_罗宾汉_哈勃_后勤英雄',
	answer = 'Question46',
	associatedID = '44_45',
	des = 'QuestionName46',
	infor = 'StrategyInfor46',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513714'
},
[47] ={
	id = 47,
	name = '@QuestionName47',
	keyWordsID = '皮肤_装扮',
	answer = 'Question47',
	associatedID = '27_66',
	des = 'QuestionName47',
	infor = 'StrategyInfor47',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6541580'
},
[48] ={
	id = 48,
	name = '@QuestionName48',
	keyWordsID = '升级芯片_芯片升级',
	answer = 'Question48',
	des = 'QuestionName48',
	infor = 'StrategyInfor48',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513752'
},
[49] ={
	id = 49,
	name = '@QuestionName49',
	keyWordsID = '军事芯片',
	answer = 'Question49',
	associatedID = '48_50_51',
	des = 'QuestionName49',
	infor = 'StrategyInfor49',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513752'
},
[50] ={
	id = 50,
	name = '@QuestionName50',
	keyWordsID = '工业芯片',
	answer = 'Question50',
	associatedID = '48_49_51',
	des = 'QuestionName50',
	infor = 'StrategyInfor50',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513752'
},
[51] ={
	id = 51,
	name = '@QuestionName51',
	keyWordsID = '后勤芯片',
	answer = 'Question51',
	associatedID = '48_49_51',
	des = 'QuestionName51',
	infor = 'StrategyInfor51',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513752'
},
[52] ={
	id = 52,
	name = '@QuestionName52',
	keyWordsID = '芯片分解_分解芯片',
	answer = 'Question52',
	associatedID = 48,
	des = 'QuestionName52',
},
[53] ={
	id = 53,
	name = '@QuestionName53',
	keyWordsID = '采矿车',
	answer = 'Question53',
	associatedID = '19_54',
	des = 'QuestionName53',
	infor = 'StrategyInfor53',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513718'
},
[54] ={
	id = 54,
	name = '@QuestionName54',
	keyWordsID = '攻城车',
	answer = 'Question54',
	associatedID = '19_53_135_154',
	des = 'QuestionName54',
	infor = 'StrategyInfor54',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6516200'
},
[55] ={
	id = 55,
	name = '@QuestionName55',
	keyWordsID = '防御坦克_盾',
	answer = 'Question55',
	associatedID = '20_56',
	des = 'QuestionName55',
	infor = 'StrategyInfor55',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6515648'
},
[56] ={
	id = 56,
	name = '@QuestionName56',
	keyWordsID = '主战_主战坦克',
	answer = 'Question56',
	associatedID = '20_55',
	des = 'QuestionName56',
	infor = 'StrategyInfor56',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6516201'
},
[57] ={
	id = 57,
	name = '@QuestionName57',
	keyWordsID = '突击步兵',
	answer = 'Question57',
	associatedID = '21_58',
	des = 'QuestionName57',
	infor = 'StrategyInfor57',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6518546'
},
[58] ={
	id = 58,
	name = '@QuestionName58',
	keyWordsID = '狙击步兵',
	answer = 'Question58',
	associatedID = '21_57_134',
	des = 'QuestionName58',
	infor = 'StrategyInfor58',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6506574'
},
[59] ={
	id = 59,
	name = '@QuestionName59',
	keyWordsID = '轰炸机',
	answer = 'Question59',
	associatedID = '18_60_136',
	des = 'QuestionName59',
	infor = 'StrategyInfor59',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6516204'
},
[60] ={
	id = 60,
	name = '@QuestionName60',
	keyWordsID = '直升机',
	answer = 'Question60',
	associatedID = '18_59',
	des = 'QuestionName60',
	infor = 'StrategyInfor60',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6516207'
},
[61] ={
	id = 61,
	name = '@QuestionName61',
	keyWordsID = '机枪碉堡',
	answer = 'Question61',
	associatedID = '22_62_63',
	des = 'QuestionName61',
	infor = 'StrategyInfor61',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6505579'
},
[62] ={
	id = 62,
	name = '@QuestionName62',
	keyWordsID = '反坦克榴弹',
	answer = 'Question62',
	associatedID = '22_61_63',
	des = 'QuestionName62',
	infor = 'StrategyInfor62',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6505579'
},
[63] ={
	id = 63,
	name = '@QuestionName63',
	keyWordsID = '防空火炮',
	answer = 'Question63',
	associatedID = '22_61_62',
	des = 'QuestionName63',
	infor = 'StrategyInfor63',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6505579'
},
[64] ={
	id = 64,
	name = '@QuestionName64',
	keyWordsID = '野怪_野外敌军',
	answer = 'Question64',
	des = 'QuestionName64',
},
[65] ={
	id = 65,
	name = '@QuestionName65',
	keyWordsID = '打野_刷野',
	answer = 'Question65',
	associatedID = 99,
	des = 'QuestionName65',
},
[66] ={
	id = 66,
	name = '@QuestionName66',
	keyWordsID = '铭牌',
	answer = 'Question66',
	associatedID = '27_47',
	des = 'QuestionName66',
},
[67] ={
	id = 67,
	name = '@QuestionName67',
	keyWordsID = '基地_建筑工厂',
	answer = 'Question67',
	associatedID = '5_27_47_66',
	des = 'QuestionName67',
	infor = 'StrategyInfor67',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6497966'
},
[68] ={
	id = 68,
	name = '@QuestionName68',
	keyWordsID = '尤里兵营_幽灵兵营',
	answer = 'Question68',
	associatedID = '99_64',
	des = 'QuestionName68',
},
[69] ={
	id = 69,
	name = '@QuestionName69',
	keyWordsID = '矿_矿石',
	answer = 'Question69',
	associatedID = 10,
	des = 'QuestionName69',
	infor = 'StrategyInfor69',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6505637'
},
[70] ={
	id = 70,
	name = '@QuestionName70',
	keyWordsID = '油_石油',
	answer = 'Question70',
	associatedID = 11,
	des = 'QuestionName70',
	infor = 'StrategyInfor70',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6505637'
},
[71] ={
	id = 71,
	name = '@QuestionName71',
	keyWordsID = '铁_合金',
	answer = 'Question71',
	associatedID = 13,
	des = 'QuestionName71',
	infor = 'StrategyInfor71',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6505637'
},
[72] ={
	id = 72,
	name = '@QuestionName72',
	keyWordsID = '土_稀土',
	answer = 'Question72',
	associatedID = 12,
	des = 'QuestionName72',
	infor = 'StrategyInfor72',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6505637'
},
[73] ={
	id = 73,
	name = '@QuestionName73',
	keyWordsID = '幽灵基地_尖塔',
	answer = 'Question73',
	des = 'QuestionName73',
},
[74] ={
	id = 74,
	name = '@QuestionName74',
	keyWordsID = '战区_北部战区_西北战区_东北战区_西部战区_东部战区_西南战区_东南战区_南部战区',
	answer = 'Question74',
	associatedID = 139,
	des = 'QuestionName74',
	infor = 'StrategyInfor74',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6530967'
},
[75] ={
	id = 75,
	name = '@QuestionName75',
	keyWordsID = '盟军总部_国王_司令_盟军司令',
	answer = 'Question75',
	des = 'QuestionName75',
	infor = 'StrategyInfor75',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348520'
},
[76] ={
	id = 76,
	name = '@QuestionName76',
	keyWordsID = '黑土地_战争区域',
	answer = 'Question76',
	des = 'QuestionName76',
},
[77] ={
	id = 77,
	name = '@QuestionName77',
	keyWordsID = '资源带_高级资源',
	answer = 'Question77',
	des = 'QuestionName77',
	infor = 'StrategyInfor77',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6505637'
},
[78] ={
	id = 78,
	name = '@QuestionName78',
	keyWordsID = '日常任务_每日任务_任务',
	answer = 'Question78',
	associatedID = 79,
	des = 'QuestionName78',
},
[79] ={
	id = 79,
	name = '@QuestionName79',
	keyWordsID = '使命_使命任务',
	answer = 'Question79',
	des = 'QuestionName79',
},
[80] ={
	id = 80,
	name = '@QuestionName80',
	keyWordsID = '战略_天赋',
	answer = 'Question80',
	associatedID = '81_82_83',
	des = 'QuestionName80',
	infor = 'StrategyInfor80',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513732'
},
[81] ={
	id = 81,
	name = '@QuestionName81',
	keyWordsID = '军事战略_军事天赋',
	answer = 'Question81',
	associatedID = '82_83',
	des = 'QuestionName81',
	infor = 'StrategyInfor81',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6499904'
},
[82] ={
	id = 82,
	name = '@QuestionName82',
	keyWordsID = '工业战略_工业天赋',
	answer = 'Question82',
	associatedID = '81_83',
	des = 'QuestionName82',
	infor = 'StrategyInfor82',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6499904'
},
[83] ={
	id = 83,
	name = '@QuestionName83',
	keyWordsID = '后勤战略_后勤天赋',
	answer = 'Question83',
	associatedID = '81_82',
	des = 'QuestionName83',
	infor = 'StrategyInfor83',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6499904'
},
[84] ={
	id = 84,
	name = '@QuestionName84',
	keyWordsID = '成就',
	answer = 'Question84',
	des = 'QuestionName84',
	infor = 'StrategyInfor84',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513732'
},
[85] ={
	id = 85,
	name = '@QuestionName85',
	keyWordsID = '战斗力_战力',
	answer = 'Question85',
	associatedID = 4,
	des = 'QuestionName85',
},
[86] ={
	id = 86,
	name = '@QuestionName86',
	keyWordsID = '签名',
	answer = 'Question86',
	des = 'QuestionName86',
},
[87] ={
	id = 87,
	name = '@QuestionName87',
	keyWordsID = '形象',
	answer = 'Question87',
	des = 'QuestionName87',
	infor = 'StrategyInfor87',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513732'
},
[88] ={
	id = 88,
	name = '@QuestionName88',
	keyWordsID = '名称_改名',
	answer = 'Question88',
	des = 'QuestionName88',
	infor = 'StrategyInfor88',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513732'
},
[89] ={
	id = 89,
	name = '@QuestionName89',
	keyWordsID = '头像',
	answer = 'Question89',
	des = 'QuestionName89',
	infor = 'StrategyInfor89',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513732'
},
[90] ={
	id = 90,
	name = '@QuestionName90',
	keyWordsID = '建筑队列',
	answer = 'Question90',
	des = 'QuestionName90',
},
[91] ={
	id = 91,
	name = '@QuestionName91',
	keyWordsID = '行军队列',
	answer = 'Question91',
	des = 'QuestionName91',
},
[92] ={
	id = 92,
	name = '@QuestionName92',
	keyWordsID = '联盟',
	answer = 'Question92',
	associatedID = '106_107_108_109',
	des = 'QuestionName92',
	infor = 'StrategyInfor92',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6506566'
},
[93] ={
	id = 93,
	name = '@QuestionName93',
	keyWordsID = '邮件',
	answer = 'Question93',
	des = 'QuestionName93',
	infor = 'StrategyInfor93',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6521620'
},
[94] ={
	id = 94,
	name = '@QuestionName94',
	keyWordsID = '贵族_贵族等级_贵族商城_贵族经验',
	answer = 'Question94',
	des = 'QuestionName94',
	infor = 'StrategyInfor94',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6516202'
},
[95] ={
	id = 95,
	name = '@QuestionName95',
	keyWordsID = '侦察',
	answer = 'Question95',
	associatedID = 28,
	des = 'QuestionName95',
	infor = 'StrategyInfor95',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6534956'
},
[96] ={
	id = 96,
	name = '@QuestionName96',
	keyWordsID = ' 集结',
	answer = 'Question96',
	associatedID = 31,
	des = 'QuestionName96',
	infor = 'StrategyInfor96',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6506566'
},
[97] ={
	id = 97,
	name = '@QuestionName97',
	keyWordsID = '高迁_精准传送_精传_高传',
	answer = 'Question97',
	des = 'QuestionName97',
},
[98] ={
	id = 98,
	name = '@QuestionName98',
	keyWordsID = '随飞_随机传送',
	answer = 'Question98',
	des = 'QuestionName98',
},
[99] ={
	id = 99,
	name = '@QuestionName99',
	keyWordsID = '体力',
	answer = 'Question99',
	associatedID = '65_68',
	des = 'QuestionName99',
},
[100] ={
	id = 100,
	name = '@QuestionName100',
	keyWordsID = '指挥官经验',
	answer = 'Question100',
	associatedID = 80,
	des = 'QuestionName100',
},
[101] ={
	id = 101,
	name = '@QuestionName101',
	keyWordsID = '伤兵',
	answer = 'Question101',
	des = 'QuestionName101',
},
[102] ={
	id = 102,
	name = '@QuestionName102',
	keyWordsID = '死兵',
	answer = 'Question102',
	des = 'QuestionName102',
},
[103] ={
	id = 103,
	name = '@QuestionName103',
	keyWordsID = '安全资源_保护资源',
	answer = 'Question103',
	associatedID = 104,
	des = 'QuestionName103',
	infor = 'StrategyInfor103',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6501404'
},
[104] ={
	id = 104,
	name = '@QuestionName104',
	keyWordsID = '非安全资源_非保资源',
	answer = 'Question104',
	associatedID = '17_40_103',
	des = 'QuestionName104',
	infor = 'StrategyInfor104',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6501404'
},
[105] ={
	id = 105,
	name = '@QuestionName105',
	keyWordsID = '防护罩_保护罩_罩子_时空屏障',
	answer = 'Question105',
	des = 'QuestionName105',
},
[106] ={
	id = 106,
	name = '@QuestionName106',
	keyWordsID = '联盟宝藏_宝箱',
	answer = 'Question106',
	associatedID = 92,
	des = 'QuestionName106',
	infor = 'StrategyInfor106',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6522035'
},
[107] ={
	id = 107,
	name = '@QuestionName107',
	keyWordsID = '联盟礼物',
	answer = 'Question107',
	associatedID = 92,
	des = 'QuestionName107',
	infor = 'StrategyInfor107',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348520'
},
[108] ={
	id = 108,
	name = '@QuestionName108',
	keyWordsID = '联盟科技',
	answer = 'Question108',
	associatedID = 92,
	des = 'QuestionName108',
	infor = 'StrategyInfor108',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6521607'
},
[109] ={
	id = 109,
	name = '@QuestionName109',
	keyWordsID = '联盟商店',
	answer = 'Question109',
	associatedID = 92,
	des = 'QuestionName109',
	infor = 'StrategyInfor109',
	url = 'https://hongjing.qq.com/ingame/all/vdetail.shtml?vid=348520'
},
[110] ={
	id = 110,
	name = '@QuestionName110',
	keyWordsID = '卡维利',
	answer = 'Question110',
	des = 'QuestionName110',
},
[111] ={
	id = 111,
	name = '@QuestionName111',
	keyWordsID = '伏尔加',
	answer = 'Question111',
	des = 'QuestionName111',
	infor = 'StrategyInfor111',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6534451'
},
[112] ={
	id = 112,
	name = '@QuestionName112',
	keyWordsID = '谭雅',
	answer = 'Question112',
	des = 'QuestionName112',
	infor = 'StrategyInfor112',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6533804'
},
[113] ={
	id = 113,
	name = '@QuestionName113',
	keyWordsID = '鲍里斯',
	answer = 'Question113',
	des = 'QuestionName113',
	infor = 'StrategyInfor113',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6534447'
},
[114] ={
	id = 114,
	name = '@QuestionName114',
	keyWordsID = '加特林',
	answer = 'Question114',
	des = 'QuestionName114',
},
[115] ={
	id = 115,
	name = '@QuestionName115',
	keyWordsID = '凤凰',
	answer = 'Question115',
	des = 'QuestionName115',
},
[116] ={
	id = 116,
	name = '@QuestionName116',
	keyWordsID = '黑寡妇',
	answer = 'Question116',
	des = 'QuestionName116',
},
[117] ={
	id = 117,
	name = '@QuestionName117',
	keyWordsID = '驻防',
	answer = 'Question117',
	des = 'QuestionName117',
	infor = 'StrategyInfor117',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6518554'
},
[118] ={
	id = 118,
	name = '@QuestionName118',
	keyWordsID = '委任_任命',
	answer = 'Question118',
	des = 'QuestionName118',
	infor = 'StrategyInfor118',
	url = 'https://hongjing.qq.com/ingame/all/detail.shtml?nid=6513714'
},
[119] ={
	id = 119,
	name = '@QuestionName119',
	keyWordsID = '喀秋莎',
	answer = 'Question119',
	des = 'QuestionName119',
},
[120] ={
	id = 120,
	name = '@QuestionName120',
	keyWordsID = '超能实验室',
	answer = 'Question120',
	associatedID = 121,
	des = 'QuestionName120',
},
[121] ={
	id = 121,
	name = '@QuestionName121',
	keyWordsID = '能量_能量源',
	answer = 'Question121',
	associatedID = 120,
	des = 'QuestionName121',
},
[122] ={
	id = 122,
	name = '@QuestionName122',
	keyWordsID = '机甲要塞_要塞',
	answer = 'Question122',
	associatedID = '123_124_125_126_127_128',
	des = 'QuestionName122',
},
[123] ={
	id = 123,
	name = '@QuestionName123',
	keyWordsID = '警戒',
	answer = 'Question123',
	des = 'QuestionName123',
},
[124] ={
	id = 124,
	name = '@QuestionName124',
	keyWordsID = '改装_进阶',
	answer = 'Question124',
	des = 'QuestionName124',
},
[125] ={
	id = 125,
	name = '@QuestionName125',
	keyWordsID = '金刚',
	answer = 'Question125',
	associatedID = '126_127_128',
	des = 'QuestionName125',
},
[126] ={
	id = 126,
	name = '@QuestionName126',
	keyWordsID = '泰坦_泰坦风暴_坦克机甲',
	answer = 'Question126',
	associatedID = '125_127_128',
	des = 'QuestionName126',
},
[127] ={
	id = 127,
	name = '@QuestionName127',
	keyWordsID = '毁灭者_步兵机甲',
	answer = 'Question127',
	associatedID = '125_126_128',
	des = 'QuestionName127',
},
[128] ={
	id = 128,
	name = '@QuestionName128',
	keyWordsID = '自由之翼_空军机甲_飞行机甲',
	answer = 'Question128',
	associatedID = '125_126_127',
	des = 'QuestionName128',
},
[129] ={
	id = 129,
	name = '@QuestionName129',
	keyWordsID = '勇士殿堂_试练场',
	answer = 'Question129',
	des = 'QuestionName129',
},
[130] ={
	id = 130,
	name = '@QuestionName130',
	keyWordsID = '赏金猎人',
	answer = 'Question130',
	des = 'QuestionName130',
},
[131] ={
	id = 131,
	name = '@QuestionName131',
	keyWordsID = '勋章',
	answer = 'Question131',
	associatedID = 132,
	des = 'QuestionName131',
},
[132] ={
	id = 132,
	name = '@QuestionName132',
	keyWordsID = '勋章兵种',
	answer = 'Question132',
	associatedID = 131,
	des = 'QuestionName132',
},
[133] ={
	id = 133,
	name = '@QuestionName133',
	keyWordsID = '所罗门',
	answer = 'Question133',
	des = 'QuestionName133',
},
[134] ={
	id = 134,
	name = '@QuestionName134',
	keyWordsID = '艾薇儿',
	answer = 'Question134',
	des = 'QuestionName134',
},
[135] ={
	id = 135,
	name = '@QuestionName135',
	keyWordsID = '贾斯汀',
	answer = 'Question135',
	des = 'QuestionName135',
},
[136] ={
	id = 136,
	name = '@QuestionName136',
	keyWordsID = '莉塔',
	answer = 'Question136',
	des = 'QuestionName136',
},
[137] ={
	id = 137,
	name = '@QuestionName137',
	keyWordsID = '杰洛特',
	answer = 'Question137',
	des = 'QuestionName137',
},
[138] ={
	id = 138,
	name = '@QuestionName138',
	keyWordsID = '天赋',
	answer = 'Question138',
	des = 'QuestionName138',
},
[139] ={
	id = 139,
	name = '@QuestionName139',
	keyWordsID = '战区赛季',
	answer = 'Question139',
	des = 'QuestionName139',
},
[140] ={
	id = 140,
	name = '@QuestionName140',
	keyWordsID = '航海远征_跨服',
	answer = 'Question140',
	des = 'QuestionName140',
},
[141] ={
	id = 141,
	name = '@QuestionName141',
	keyWordsID = '战地为王_插旗',
	answer = 'Question141',
	des = 'QuestionName141',
},
[142] ={
	id = 142,
	name = '@QuestionName142',
	keyWordsID = '联合军演_军演',
	answer = 'Question142',
	des = 'QuestionName142',
},
[143] ={
	id = 143,
	name = '@QuestionName143',
	keyWordsID = '卡洛琳',
	answer = 'Question143',
	des = 'QuestionName143',
},
[144] ={
	id = 144,
	name = '@QuestionName144',
	keyWordsID = '特斯拉',
	answer = 'Question144',
	des = 'QuestionName144',
},
[145] ={
	id = 145,
	name = '@QuestionName145',
	keyWordsID = '马库斯',
	answer = 'Question145',
	des = 'QuestionName145',
},
[146] ={
	id = 146,
	name = '@QuestionName146',
	keyWordsID = '泰伯利亚战争_征服之地_泰伯利亚',
	answer = 'Question146',
	des = 'QuestionName146',
},
[147] ={
	id = 147,
	name = '@QuestionName147',
	keyWordsID = '装备',
	answer = 'Question147',
	associatedID = '148_149_150_151_152',
	des = 'QuestionName147',
},
[148] ={
	id = 148,
	name = '@QuestionName148',
	keyWordsID = '装备套装_套装',
	answer = 'Question148',
	associatedID = '147_149_150_151_152',
	des = 'QuestionName148',
},
[149] ={
	id = 149,
	name = '@QuestionName149',
	keyWordsID = '装扮品质',
	answer = 'Question149',
	associatedID = '147_148_150_151_152',
	des = 'QuestionName149',
},
[150] ={
	id = 150,
	name = '@QuestionName150',
	keyWordsID = '装备强化',
	answer = 'Question150',
	associatedID = '147_148_149_151_152',
	des = 'QuestionName150',
},
[151] ={
	id = 151,
	name = '@QuestionName151',
	keyWordsID = '装备传承',
	answer = 'Question151',
	associatedID = '147_148_149_150_152',
	des = 'QuestionName151',
},
[152] ={
	id = 152,
	name = '@QuestionName152',
	keyWordsID = '装备突破',
	answer = 'Question152',
	associatedID = '147_148_149_150_151',
	des = 'QuestionName152',
},
[153] ={
	id = 153,
	name = '@QuestionName153',
	keyWordsID = '凯恩',
	answer = 'Question153',
	des = 'QuestionName153',
},
[154] ={
	id = 154,
	name = '@QuestionName154',
	keyWordsID = '爱莉莎',
	answer = 'Question154',
	des = 'QuestionName154',
},
[155] ={
	id = 155,
	name = '@QuestionName155',
	keyWordsID = '希伯特',
	answer = 'Question155',
	des = 'QuestionName155',
},
[156] ={
	id = 156,
	name = '@QuestionName156',
	keyWordsID = '星云_星云机甲_攻城车机甲',
	answer = 'Question156',
	associatedID = '125_126_127_128',
	des = 'QuestionName156',
},
[157] ={
	id = 157,
	name = '@QuestionName157',
	keyWordsID = '克瑞斯',
	answer = 'Question157',
	des = 'QuestionName157',
},
[158] ={
	id = 158,
	name = '@QuestionName158',
	keyWordsID = '吉丽安',
	answer = 'Question158',
	des = 'QuestionName158',
},
[159] ={
	id = 159,
	name = '@QuestionName159',
	keyWordsID = '泰能建筑',
	answer = 'Question159',
	des = 'QuestionName159',
},
[160] ={
	id = 160,
	name = '@QuestionName160',
	keyWordsID = '泰能战士',
	answer = 'Question160',
	des = 'QuestionName160',
}
}
return question_conf
