--[[
     雷达显示控制表
     author: Leoli
     -----------------------------
     level          -- 雷达等级
     name           -- 指挥官名字
     commanderLevel -- 指挥官等级
     purpose        -- 行军目的
     coord          -- 坐标
     progress       -- 进度条
     armyTotal      -- 部队总数
     armyType       -- 部队类型
     armyDetail     -- 部队详细数量
     tech           -- 科技
     talent         -- 天赋
     -----------------------------
  ]]
local radar_show_conf = {
[1] ={
     level          = 1,
     name           = true,
     commanderLevel = false,
     purpose        = true,
     coord          = false,
     progress       = false,
     armyTotal      = false,
     armyType       = false,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[2] ={
     level          = 2,
     name           = true,
     commanderLevel = false,
     purpose        = true,
     coord          = false,
     progress       = false,
     armyTotal      = false,
     armyType       = false,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[3] ={
     level          = 3,
     name           = true,
     commanderLevel = false,
     purpose        = true,
     coord          = true,
     progress       = false,
     armyTotal      = false,
     armyType       = false,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[4] ={
     level          = 4,
     name           = true,
     commanderLevel = false,
     purpose        = true,
     coord          = true,
     progress       = false,
     armyTotal      = false,
     armyType       = false,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[5] ={
     level          = 5,
     name           = true,
     commanderLevel = false,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = false,
     armyType       = false,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[6] ={
     level          = 6,
     name           = true,
     commanderLevel = false,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = false,
     armyType       = false,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[7] ={
     level          = 7,
     name           = true,
     commanderLevel = false,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = false,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[8] ={
     level          = 8,
     name           = true,
     commanderLevel = false,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = false,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[9] ={
     level          = 9,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = false,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[10] ={
     level          = 10,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = false,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[11] ={
     level          = 11,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[12] ={
     level          = 12,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = false,
     tech           = false,
     talent         = false,
},
[13] ={
     level          = 13,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[14] ={
     level          = 14,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[15] ={
     level          = 15,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[16] ={
     level          = 16,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[17] ={
     level          = 17,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[18] ={
     level          = 18,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[19] ={
     level          = 19,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[20] ={
     level          = 20,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[21] ={
     level          = 21,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[22] ={
     level          = 22,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[23] ={
     level          = 23,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[24] ={
     level          = 24,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[25] ={
     level          = 25,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = false,
     talent         = false,
},
[26] ={
     level          = 26,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = false,
},
[27] ={
     level          = 27,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = false,
},
[28] ={
     level          = 28,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = false,
},
[29] ={
     level          = 29,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = true,
},
[30] ={
     level          = 30,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = true,
},
[31] ={
     level          = 31,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = true,
},
[32] ={
     level          = 32,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = true,
},
[33] ={
     level          = 33,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = true,
},
[34] ={
     level          = 34,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = true,
},
[35] ={
     level          = 35,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = true,
},
[36] ={
     level          = 36,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = true,
},
[37] ={
     level          = 37,
     name           = true,
     commanderLevel = true,
     purpose        = true,
     coord          = true,
     progress       = true,
     armyTotal      = true,
     armyType       = true,
     armyDetail     = true,
     tech           = true,
     talent         = true,
},
[38] ={
	level = 38,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[39] ={
	level = 39,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[40] ={
	level = 40,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[41] ={
	level = 41,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[42] ={
	level = 42,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[43] ={
	level = 43,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[44] ={
	level = 44,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[45] ={
	level = 45,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[46] ={
	level = 46,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[47] ={
	level = 47,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[48] ={
	level = 48,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[49] ={
	level = 49,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
},
[50] ={
	level = 50,
	name = 'true',
	commanderLevel = 'true',
	purpose = 'true',
	coord = 'true',
	progress = 'true',
	armyTotal = 'true',
	armyType = 'true',
	armyDetail = 'true',
	tech = 'true',
	talent = 'true'
}
}
return radar_show_conf
