local setting_option_conf = {
['option_shopConsume'] ={
	id = 'option_shopConsume',
	name = '@SettingOption_shopConsume',
	type = 1,
	priority = 1,
	isshow = 0,
	type_name = '@SettingOption_ConsumeTitle',
	isClientSave = 1,
},
['option_buildingLevelUpConsume'] ={
	id = 'option_buildingLevelUpConsume',
	name = '@SettingOption_buildingLevelUpConsume',
	type = 1,
	priority = 2,
	isshow = 0,
	type_name = '@SettingOption_ConsumeTitle',
	isClientSave = 1,
},
['option_cureSoldierConsume'] ={
	id = 'option_cureSoldierConsume',
	name = '@SettingOption_cureSoldierConsume',
	type = 1,
	priority = 3,
	isshow = 0,
	type_name = '@SettingOption_ConsumeTitle',
	isClientSave = 1,
},
['option_trainSoldierConsume'] ={
	id = 'option_trainSoldierConsume',
	name = '@SettingOption_trainSoldierConsume',
	type = 1,
	priority = 4,
	isshow = 0,
	type_name = '@SettingOption_ConsumeTitle',
	isClientSave = 1,
},
['option_buildingRepairConsume'] ={
	id = 'option_buildingRepairConsume',
	name = '@SettingOption_buildingRepairConsume',
	type = 1,
	priority = 5,
	isshow = 0,
	type_name = '@SettingOption_ConsumeTitle',
	isClientSave = 1,
},
['option_buildingRebuildConsume'] ={
	id = 'option_buildingRebuildConsume',
	name = '@SettingOption_buildingRebuildConsume',
	type = 1,
	priority = 6,
	isshow = 0,
	type_name = '@SettingOption_ConsumeTitle',
	isClientSave = 1,
},
['option_researchConsume'] ={
	id = 'option_researchConsume',
	name = '@SettingOption_researchConsume',
	type = 1,
	priority = 7,
	isshow = 0,
	type_name = '@SettingOption_ConsumeTitle',
	isClientSave = 1,
},
['option_exchangeCrystal'] ={
	id = 'option_exchangeCrystal',
	name = '@SettingOption_exchangeCrystal',
	type = 1,
	priority = 8,
	isshow = 0,
	type_name = '@SettingOption_ConsumeTitle',
	isClientSave = 1,
},
['option_showBloodBar'] ={
	id = 'option_showBloodBar',
	name = '@SettingOption_option_ShowBloodBar',
	type = 2,
	priority = 9,
	isshow = 0,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 1,
},
['option_setGameQuality'] ={
	id = 'option_setGameQuality',
	name = '@SettingOption_option_SetGameQuality',
	type = 2,
	priority = 10,
	isshow = 1,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 1,
	desc = '@SettingOption_option_SetGameQuality_Desc'
},
['option_setWorldAngleOfView'] ={
	id = 'option_setWorldAngleOfView',
	name = '@SettingOption_option_setWorldAngleOfView',
	type = 2,
	priority = 11,
	isshow = 1,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 0,
	desc = '@SettingOption_option_setWorldAngleOfView_Desc'
},
['option_selectpriority'] ={
	id = 'option_selectpriority',
	name = '@SettingOption_option_selectpriority',
	type = 2,
	priority = 12,
	isshow = 1,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 0,
	desc = '@SettingOption_option_selectpriority_Desc'
},
['option_VipHidden'] ={
	id = 'option_VipHidden',
	name = '@SettingOption_option_VipHidden',
	type = 2,
	priority = 13,
	isshow = 0,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 1,
	desc = '@SettingOption_option_VipHidden_Desc'
},
['option_PlatformVipHidden'] ={
	id = 'option_PlatformVipHidden',
	name = '@SettingOption_option_PlatformVipHidden',
	type = 2,
	priority = 14,
	isshow = 0,
	type_name = '@SettingOption_OtherTitle',
	typePartition = '1',
	isClientSave = 1,
	desc = '@SettingOption_option_PlatformVipHidden_Desc'
},
['option_music'] ={
	id = 'option_music',
	name = '@SettingOption_Music',
	type = 3,
	priority = 15,
	isshow = 1,
	type_name = '@SettingOption_MusicTitle',
	isClientSave = 0,
},
['option_effect'] ={
	id = 'option_effect',
	name = '@SettingOption_Effect',
	type = 3,
	priority = 16,
	isshow = 1,
	type_name = '@SettingOption_MusicTitle',
	typePartition = '1',
	isClientSave = 0,
},
['option_upgradeMark'] ={
	id = 'option_upgradeMark',
	name = '@SettingOption_upgradeMark',
	type = 4,
	priority = 17,
	isshow = 0,
	type_name = '@SettingOption_HintTitle',
	isClientSave = 0,
},
['option_levelMark'] ={
	id = 'option_levelMark',
	name = '@SettingOption_levelMark',
	type = 4,
	priority = 18,
	isshow = 0,
	type_name = '@SettingOption_HintTitle',
	isClientSave = 0,
},
['option_missionMark'] ={
	id = 'option_missionMark',
	name = '@SettingOption_missionMark',
	type = 4,
	priority = 19,
	isshow = 0,
	type_name = '@SettingOption_HintTitle',
	isClientSave = 0,
},
['option_costDiamond'] ={
	id = 'option_costDiamond',
	name = '@SettingOption_costDiamond',
	type = 4,
	priority = 20,
	isshow = 0,
	type_name = '@SettingOption_HintTitle',
	typePartition = '1',
	isClientSave = 0,
},
['option_musicVolume'] ={
	id = 'option_musicVolume',
	name = '@SettingOption_MusicVolume',
	type = 5,
	priority = 21,
	isshow = 1,
	type_name = '@SettingOption_VolumeTitle',
	isClientSave = 1,
	minValue = 0,
	maxValue = 1000,
	defaultValue = 1000,
},
['option_effectVolume'] ={
	id = 'option_effectVolume',
	name = '@SettingOption_EffectVolume',
	type = 5,
	priority = 22,
	isshow = 1,
	type_name = '@SettingOption_VolumeTitle',
	isClientSave = 1,
	minValue = 0,
	maxValue = 1000,
	defaultValue = 1000,
},
['option_anchorVolume'] ={
	id = 'option_anchorVolume',
	name = '@SettingOption_AnchorVolume',
	type = 5,
	priority = 23,
	isshow = 0,
	type_name = '@SettingOption_VolumeTitle',
	typePartition = '1',
	isIOSVerify = 'true',
	isClientSave = 1,
	minValue = 0,
	maxValue = 800,
	defaultValue = 800,
},
['option_pushCityInfo'] ={
	id = 'option_pushCityInfo',
	name = '@SettingOption_pushCityInfo',
	type = 6,
	priority = 24,
	isshow = 0,
	type_name = '@SettingOption_PushTitle',
	isClientSave = 0,
},
['option_pushWorldInfo'] ={
	id = 'option_pushWorldInfo',
	name = '@SettingOption_pushWorldInfo',
	type = 6,
	priority = 25,
	isshow = 0,
	type_name = '@SettingOption_PushTitle',
	isClientSave = 0,
},
['option_pushAllianceInfo'] ={
	id = 'option_pushAllianceInfo',
	name = '@SettingOption_pushAllianceInfo',
	type = 6,
	priority = 26,
	isshow = 0,
	type_name = '@SettingOption_PushTitle',
	isClientSave = 0,
},
['option_pushSocialInfo'] ={
	id = 'option_pushSocialInfo',
	name = '@SettingOption_pushSocialInfo',
	type = 6,
	priority = 27,
	isshow = 0,
	type_name = '@SettingOption_PushTitle',
	isClientSave = 0,
},
['option_pushVipInfo'] ={
	id = 'option_pushVipInfo',
	name = '@SettingOption_pushVipInfo',
	type = 6,
	priority = 28,
	isshow = 0,
	type_name = '@SettingOption_PushTitle',
	isClientSave = 0,
},
['option_pushRewardInfo'] ={
	id = 'option_pushRewardInfo',
	name = '@SettingOption_pushRewardInfo',
	type = 6,
	priority = 29,
	isshow = 0,
	type_name = '@SettingOption_PushTitle',
	isClientSave = 0,
},
['option_quickspeed'] ={
	id = 'option_quickspeed',
	name = '@SettingOption_option_quickspeed',
	type = 2,
	priority = 30,
	isshow = 1,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 0,
	desc = '@SettingOption_option_quickspeed_Desc'
},
['option_quickitem'] ={
	id = 'option_quickitem',
	name = '@SettingOption_quickitem',
	type = 2,
	priority = 31,
	isshow = 0,
	baseLevel = 12,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 0,
	desc = '@SettingOption_option_quickitem_Desc'
},
['option_dressAsk'] ={
	id = 'option_dressAsk',
	name = '@SettingOption_dressAsk',
	type = 2,
	priority = 32,
	isshow = 1,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 0,
	desc = '@SettingOption_dressAsk_des'
},
['option_daltonism'] ={
	id = 'option_daltonism',
	name = '@SettingOption_daltonism',
	type = 2,
	priority = 33,
	isshow = 1,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 1,
	desc = '@SettingOption_daltonism_des'
},
['option_FixedNavigation'] ={
	id = 'option_FixedNavigation',
	name = '@SettingOption_FixedNavigation',
	type = 2,
	priority = 34,
	isshow = 1,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 1,
	desc = '@SettingOption_FixedNavigation_des'
},
-- ['option_Cancellation'] entry removed: account-cancellation feature disabled.
['option_dressShow'] ={
	id = 'option_dressShow',
	name = '@SettingOption_dressShow',
	type = 2,
	priority = 36,
	isshow = 1,
	type_name = '@SettingOption_dressShowTitle',
	isClientSave = 1,
	desc = '@SettingOption_dressShowDes'
},
['option_HelpOther'] ={
	id = 'option_HelpOther',
	name = '@SettingOption_HelpOther',
	type = 2,
	priority = 37,
	isshow = 1,
	type_name = '@SettingOption_HelpOtherTitle',
	isClientSave = 0,
	desc = '@SettingOption_HelpOtherDes'
},
['option_AutoFixSoldier'] ={
	id = 'option_AutoFixSoldier',
	name = '@SettingOption_AutoFixSoldier',
	type = 6,
	priority = 38,
	isshow = 1,
	type_name = '@SettingOption_AutoFixSoldier',
	isClientSave = 1,
	desc = '@SettingOption_AutoFixSoldier_des'
},
['option_tblyNotice'] ={
	id = 'option_tblyNotice',
	name = '@SettingOption_tblyNotice',
	type = 2,
	priority = 39,
	isshow = 1,
	type_name = '@SettingOption_tblyNoticeTitle',
	isClientSave = 1,
	desc = '@SettingOption_tblyNoticeDesc'
},
['option_MANEffectShow'] ={
	id = 'option_MANEffectShow',
	name = '@SettingOption_MANAttackEffectShow',
	type = 2,
	priority = 40,
	isshow = 0,
	type_name = '@SettingOption_MANAttackEffectShow',
	isClientSave = 0,
},
['option_LuxuryNotice'] ={
	id = 'option_LuxuryNotice',
	name = '@SettingOption_luxuryNotice',
	type = 2,
	priority = 41,
	isshow = 1,
	type_name = '@SettingOption_OtherTitle',
	isClientSave = 0,
	desc = '@SettingOption_luxuryNotice_Desc'
}
}
return setting_option_conf
