local world_HUD_conf = {
[1] ={
	id = 1,
	btn = 'AddFavorite',
	name = '@Migrate',
	icon = 'HUD_MoveCity.png',
	priority = 1,
},
[2] ={
	id = 2,
	btn = 'Migrate',
	name = '@Migrate',
	icon = 'HUD_MoveCity.png',
	priority = 2,
	HUDSound = 'UI_SFX_S_ClickDetermine'
},
[3] ={
	id = 3,
	btn = 'Settle',
	name = '@Settle',
	icon = 'HUD_AllianceTerritory.png',
	priority = 3,
},
[4] ={
	id = 4,
	btn = 'InviteToMigrate',
	name = '@InviteToMigrate',
	icon = 'HUD_InviteMoveCity.png',
	priority = 4,
},
[5] ={
	id = 5,
	btn = 'Occupy',
	name = '@Occupy',
	icon = 'HUD_Occupy.png',
	priority = 5,
	HUDSound = 'COMMON_BTN_Click_1'
},
[6] ={
	id = 6,
	btn = 'EnterCity',
	name = '@EnterCity',
	icon = 'HUD_City.png',
	priority = 6,
},
[7] ={
	id = 7,
	btn = 'CityGain',
	name = '@CityGain',
	icon = 'HUD_CityGain.png',
	priority = 7,
},
[8] ={
	id = 8,
	btn = 'Attack',
	name = '@DoAttack',
	icon = 'HUD_Attack.png',
	priority = 8,
	HUDSound = 'BTN_StartGame'
},
[9] ={
	id = 9,
	btn = 'Spy',
	name = '@Spy',
	icon = 'HUD_Spy.png',
	priority = 9,
},
[10] ={
	id = 10,
	btn = 'GeneralDetail',
	name = '@GeneralDetail',
	icon = 'HUD_GeneralDetails.png',
	priority = 94,
},
[11] ={
	id = 11,
	btn = 'CancelMigrate',
	name = '@Cancel',
	icon = 'HUD_CancelMoveCity.png',
	priority = 11,
},
[12] ={
	id = 12,
	btn = 'MarchSpeedUp',
	name = '@SpeedUp',
	icon = 'HUD_MarchAccelerate.png',
	priority = 12,
},
[13] ={
	id = 13,
	btn = 'MarchRecall',
	name = '@SpeedUp',
	icon = 'HUD_MarchRecall.png',
	priority = 13,
},
[14] ={
	id = 14,
	btn = 'MarchArmyDetail',
	name = '@SpeedUp',
	icon = 'HUD_ArmyDetails.png',
	priority = 14,
},
[15] ={
	id = 15,
	btn = 'SoldierAid',
	name = '@SoldierAid',
	icon = 'HUD_ArmyHelp.png',
	priority = 15,
},
[16] ={
	id = 16,
	btn = 'ResourceAid',
	name = '@ResourceAid',
	icon = 'HUD_ResHelp.png',
	priority = 16,
},
[17] ={
	id = 17,
	btn = 'DeclareWar',
	name = '@DeclareWar',
	icon = 'HUD_Gather.png',
	priority = 18,
},
[18] ={
	id = 18,
	btn = 'Recall',
	name = '@Recall',
	icon = 'HUD_MarchRecall.png',
	priority = 19,
},
[19] ={
	id = 19,
	btn = 'ArmyDetail',
	name = '@TroopsInfo',
	icon = 'HUD_ArmyDetails.png',
	priority = 95,
},
[20] ={
	id = 20,
	btn = 'OccupyTerritory',
	name = '@Occupy',
	icon = 'HUD_OccupiedTerritory.png',
	priority = 20,
},
[21] ={
	id = 21,
	btn = 'QuitTerritory',
	name = '@Quit',
	icon = 'HUD_GiveUpterritory.png',
	priority = 21,
},
[22] ={
	id = 22,
	btn = 'LaunchBomb',
	name = '@LaunchBomb',
	icon = 'HUD_LaunchNuclear.png',
	priority = 17,
},
[23] ={
	id = 23,
	btn = 'CancelLaunch',
	name = '@Cancel',
	icon = 'HUD_Cancel.png',
	priority = 23,
},
[24] ={
	id = 24,
	btn = 'ViewOwnership',
	name = '@ViewOwnership',
	icon = 'HUD_CheckTerritory.png',
	priority = 24,
},
[25] ={
	id = 25,
	btn = 'OpenSilo',
	name = '@OpenSilo',
	icon = 'HUD_CheckTerritory.png',
	priority = 25,
},
[26] ={
	id = 26,
	btn = 'CloseSilo',
	name = '@CloseSilo',
	icon = 'HUD_CheckTerritory.png',
	priority = 26,
},
[27] ={
	id = 27,
	btn = 'StrongholdDetail',
	name = '@StrongholdDetail',
	icon = 'HUD_CheckTerritory.png',
	priority = 96,
},
[28] ={
	id = 28,
	btn = 'Garrison',
	name = '@Garrison',
	icon = 'HUD_WorldDefend.png',
	priority = 28,
},
[29] ={
	id = 29,
	btn = 'MassGarrison',
	name = '@MassGarrison',
	icon = 'HUD_GatherWorldDefend.png',
	priority = 29,
},
[30] ={
	id = 30,
	btn = 'Reoccupy',
	name = '@Reoccupy',
	icon = 'HUD_Recover.png',
	priority = 30,
},
[31] ={
	id = 31,
	btn = 'MassReoccupy',
	name = '@MassReoccupy',
	icon = 'HUD_GatherRecover.png',
	priority = 31,
},
[32] ={
	id = 32,
	btn = 'Reinforce',
	name = '@Reinforce',
	icon = 'HUD_WorldHelp.png',
	priority = 32,
},
[33] ={
	id = 33,
	btn = 'MassReinforce',
	name = '@MassReinforce',
	icon = 'HUD_GatherWorldHelp.png',
	priority = 33,
},
[34] ={
	id = 34,
	btn = 'Collect',
	name = '@DoCollect',
	icon = 'HUD_Collect.png',
	priority = 34,
},
[35] ={
	id = 35,
	btn = 'LaunchWeather',
	name = '@LaunchWeather',
	icon = 'HUD_LaunchNuclear.png',
	priority = 35,
},
[36] ={
	id = 36,
	btn = 'ViewDetail_President',
	name = '@ViewPresidentDetail',
	icon = 'HUD_PresidentOffice.png',
	priority = 36,
},
[37] ={
	id = 37,
	btn = 'ViewGarrison',
	name = '@ViewGarrison',
	icon = 'HUD_DefenderExplain.png',
	priority = 37,
},
[38] ={
	id = 38,
	btn = 'Appoint',
	name = '@Appointment',
	icon = 'HUD_Office.png',
	priority = 38,
},
[39] ={
	id = 39,
	btn = 'ViewGarrison_President',
	name = '@ViewGarrison',
	icon = 'HUD_DefenderExplain.png',
	priority = 39,
},
[40] ={
	id = 40,
	btn = 'Garrison_President',
	name = '@Garrison',
	icon = 'HUD_WorldDefend.png',
	priority = 40,
},
[41] ={
	id = 41,
	btn = 'MassGarrison_President',
	name = '@MassGarrison',
	icon = 'HUD_GatherWorldDefend.png',
	priority = 41,
},
[42] ={
	id = 42,
	btn = 'Recall_President',
	name = '@Recall',
	icon = 'HUD_MarchRecall.png',
	priority = 42,
},
[43] ={
	id = 43,
	btn = 'TerritoryList',
	name = '@TerritoryList',
	icon = 'HUD_CheckTerritory.png',
	priority = 43,
},
[44] ={
	id = 44,
	btn = 'ViewGarrison_Territory',
	name = '@ViewGarrison',
	icon = 'HUD_President_DefenderDetails.png',
	priority = 44,
},
[45] ={
	id = 45,
	btn = 'BuildNuclearSilo',
	name = '@BuildNuclearSilo',
	icon = 'HUD_LaunchNuclear.png',
	priority = 45,
},
[46] ={
	id = 46,
	btn = 'BuildWeatherSilo',
	name = '@BuildWeatherSilo',
	icon = 'HUD_LaunchNuclear.png',
	priority = 46,
},
[47] ={
	id = 47,
	btn = 'PlaceTerritory',
	name = '@PlaceTerritory',
	icon = 'HUD_AllianceTerritory.png',
	priority = 47,
},
[48] ={
	id = 48,
	btn = 'Repair',
	name = '@RepairBuilding',
	icon = 'HUD_Repair.png',
	priority = 48,
},
[49] ={
	id = 49,
	btn = 'Upgrade',
	name = '@Upgrade',
	icon = 'HUD_Uprgrade.png',
	priority = 49,
},
[50] ={
	id = 50,
	btn = 'ViewFunctions',
	name = '@ViewFunctions',
	icon = 'HUD_CheckFunction.png',
	priority = 98,
},
[51] ={
	id = 51,
	btn = 'DonateResource',
	name = '@DonateResource',
	icon = 'HUD_DonationRes.png',
	priority = 51,
},
[52] ={
	id = 52,
	btn = 'DepositResource',
	name = '@DepositResource',
	icon = 'HUD_SaveRes.png',
	priority = 52,
},
[53] ={
	id = 53,
	btn = 'WithdrawResource',
	name = '@WithdrawResource',
	icon = 'HUD_LoadRes.png',
	priority = 53,
},
[54] ={
	id = 54,
	btn = 'ViewArcher',
	name = '@ViewArcher',
	icon = 'HUD_CheckFunction.png',
	priority = 54,
},
[55] ={
	id = 55,
	btn = 'BuildTerritory',
	name = '@Build',
	icon = 'HUD_Construction.png',
	priority = 55,
},
[56] ={
	id = 56,
	btn = 'ViewDetail',
	name = '@ViewDetail',
	icon = 'HUD_Explain.png',
	priority = 56,
},
[57] ={
	id = 57,
	btn = 'PlaceResource',
	name = '@Settle',
	icon = 'HUD_LaunchNuclear.png',
	priority = 57,
},
[58] ={
	id = 58,
	btn = 'Explore',
	name = '@Explore',
	icon = 'HUD_Spy.png',
	priority = 58,
},
[59] ={
	id = 59,
	btn = 'PlaceRebel',
	name = '@Settle',
	icon = 'HUD_Place.png',
	priority = 59,
},
[60] ={
	id = 60,
	btn = 'LocateStartPos',
	name = '@MarchHudStart',
	icon = 'HUD_StartPosition.png',
	priority = 60,
},
[61] ={
	id = 61,
	btn = 'LocateEndPos',
	name = '@MarchHudStop',
	icon = 'HUD_EndPosition.png',
	priority = 61,
},
[62] ={
	id = 62,
	btn = 'LocateTroop',
	name = '@MarchHudTroop',
	icon = 'HUD_ArmyPosition.png',
	priority = 62,
},
[63] ={
	id = 63,
	btn = 'RemoveSource',
	name = '@RemoveResource',
	icon = 'HUD_RemoveResource.png',
	priority = 63,
},
[64] ={
	id = 64,
	btn = 'View',
	name = '@View',
	icon = 'HUD_Explain.png',
	priority = 99,
},
[65] ={
	id = 65,
	btn = 'Explain',
	name = '@Explain',
	icon = 'HUD_Explain.png',
	priority = 100,
},
[66] ={
	id = 66,
	btn = 'State',
	name = '@State',
	icon = 'HUD_Explain.png',
	priority = 64,
},
[67] ={
	id = 67,
	btn = 'Office',
	name = '@Office',
	icon = 'HUD_Office.png',
	priority = 65,
},
[68] ={
	id = 68,
	btn = 'CountryManage',
	name = '@CountryManage',
	icon = 'HUD_CountryManage.png',
	priority = 66,
},
[69] ={
	id = 69,
	btn = 'Profit',
	name = '@StrongholdEarnings',
	icon = 'HUD_SaveRes.png',
	priority = 67,
},
[70] ={
	id = 70,
	btn = 'StrongPointDetail',
	name = '@StrongholdDetails',
	icon = 'HUD_ArmyDetails.png',
	priority = 68,
},
[71] ={
	id = 71,
	btn = 'Beatback',
	name = '@Beatback',
	icon = 'HUD_Beatback.png',
	priority = 8,
	HUDSound = 'BTN_StartGame'
},
[72] ={
	id = 72,
	btn = 'MassBeatback',
	name = '@MassBeatback',
	icon = 'HUD_GatherBeatback.png',
	priority = 18,
},
[73] ={
	id = 73,
	btn = 'Dress',
	name = '@Dress',
	icon = 'HUD_Decorate.png',
	priority = 86,
},
[74] ={
	id = 74,
	btn = 'ViewDetailSuperWeapon',
	name = '@ViewDetail',
	icon = 'HUD_Explain.png',
	priority = 72,
},
[75] ={
	id = 75,
	btn = 'SignUpSuperWeapon',
	name = '@SignUp',
	icon = 'HUD_SignUp.png',
	priority = 73,
},
[76] ={
	id = 76,
	btn = 'AttackSuperWeapon',
	name = '@DoAttack',
	icon = 'HUD_Attack.png',
	priority = 74,
},
[77] ={
	id = 77,
	btn = 'SpySuperWeapon',
	name = '@Spy',
	icon = 'HUD_Spy.png',
	priority = 75,
},
[78] ={
	id = 78,
	btn = 'DeclareWarSuperWeapon',
	name = '@DeclareWar',
	icon = 'HUD_Gather.png',
	priority = 76,
},
[79] ={
	id = 79,
	btn = 'MassReinforceSuperWeapon',
	name = '@MassReinforce',
	icon = 'HUD_GatherWorldHelp.png',
	priority = 77,
},
[80] ={
	id = 80,
	btn = 'ReinforceSuperWeapon',
	name = '@Reinforce',
	icon = 'HUD_WorldHelp.png',
	priority = 78,
},
[81] ={
	id = 81,
	btn = 'RecallSuperWeapon',
	name = '@Recall',
	icon = 'HUD_MarchRecall.png',
	priority = 81,
},
[82] ={
	id = 82,
	btn = 'ArmyDetailSuperWeapon',
	name = '@TroopsInfo',
	icon = 'HUD_ArmyDetails.png',
	priority = 82,
},
[83] ={
	id = 83,
	btn = 'CollectDetails',
	name = '@CollectDetails',
	icon = 'HUD_Explain.png',
	priority = 83,
},
[84] ={
	id = 84,
	btn = 'WarRuleSuperWeapon',
	name = '@WarRuleSuperWeapon',
	icon = 'HUD_Explain.png',
	priority = 84,
},
[85] ={
	id = 85,
	btn = 'Signature',
	name = '@Signature',
	icon = 'HUD_Sign.png',
	priority = 85,
},
[86] ={
	id = 86,
	btn = 'HeroWallDefense',
	name = '@HeroDefense',
	icon = 'HUD_HeroDefense.png',
	priority = 71,
},
[87] ={
	id = 87,
	btn = 'SetAllianceSign',
	name = '@SetAllianceSign',
	icon = 'HUD_AllianceTarget.png',
	priority = 87,
},
[88] ={
	id = 88,
	btn = 'CancelAllianceSign',
	name = '@CancelAllianceSign',
	icon = 'HUD_AllianceCancelTarget.png',
	priority = 88,
},
[89] ={
	id = 89,
	btn = 'ViewIntelligence',
	name = '@ViewIntelligence',
	icon = 'HUD_DefInfo.png',
	priority = 89,
},
[90] ={
	id = 90,
	btn = 'CommanderHistory',
	name = '@CommanderHistory',
	icon = 'HUD_Office.png',
	priority = 90,
},
[91] ={
	id = 91,
	btn = 'Duel',
	name = '@talent10134hud1',
	icon = 'HUD_Deul.png',
	priority = 16,
},
[92] ={
	id = 92,
	btn = 'Transport',
	name = '@TreasuryCarry',
	icon = 'HUD_Act113_Handling.png',
	priority = 92,
},
[93] ={
	id = 93,
	btn = 'TransRecord',
	name = '@TreasuryCarryRecord',
	icon = 'HUD_Act113_Record.png',
	priority = 93,
},
[94] ={
	id = 94,
	btn = 'ResourceInfo',
	name = '@TreasuryDetails',
	icon = 'HUD_Act113_Info.png',
	priority = 94,
},
[95] ={
	id = 95,
	btn = 'TreasureInfo',
	name = '@TreasuryExplainHud',
	icon = 'HUD_Explain.png',
	priority = 95,
},
[96] ={
	id = 96,
	btn = 'CancelSignUp',
	name = '@CancelSignUp',
	icon = 'HUD_SignUp.png',
	priority = 96,
},
[97] ={
	id = 97,
	btn = 'CrossStar',
	name = '@CrossStarHud',
	icon = 'HUD_CrossServer.png',
	priority = 97,
},
[98] ={
	id = 98,
	btn = 'CollectGhostBox',
	name = '@DoCollect',
	icon = 'HUD_Collect.png',
	priority = 98,
},
[99] ={
	id = 99,
	btn = 'EmojiHUD',
	name = '@MarchEmoji',
	icon = 'HUD_MarchEmoji.png',
	priority = 99,
},
[100] ={
	id = 100,
	btn = 'SpyInfo',
	name = '@TBOBSpyInfo',
	icon = 'HUD_Spy.png',
	priority = 100,
},
[101] ={
	id = 101,
	btn = 'BattleReport',
	name = '@TBOBBattleReport',
	icon = 'HUD_Explain.png',
	priority = 101,
},
[102] ={
	id = 102,
	btn = 'KingMgr',
	name = '@KingMgr',
	icon = 'HUD_President_Mgr.png',
	priority = 102,
},
[104] ={
	id = 104,
	btn = 'ChristmasBoxCollect',
	name = '@DoCollect',
	icon = 'HUD_Collect.png',
	priority = 104,
},
[105] ={
	id = 105,
	btn = 'ChristmasBoxForceGet',
	name = '@Act163_hudforceget',
	icon = 'HUD_Collect.png',
	priority = 105,
},
[106] ={
	id = 106,
	btn = 'SnowballBomb',
	name = '@Snowball Bomb',
	icon = 'HUD_Act164_IceBall.png',
	priority = 106,
},
[107] ={
	id = 107,
	btn = 'Agent',
	name = '@Agent',
	icon = 'HUD_Act164_Spy.png',
	priority = 107,
},
[118] ={
	id = 118,
	btn = 'StarWarRoute',
	name = '@sw_tabtitle_1',
	icon = 'HUD_StarWars_Lord.png',
	priority = 119,
},
[119] ={
	id = 119,
	btn = 'StarWarPower',
	name = '@sw_tabtitle_2',
	icon = 'HUD_StarWars_Privilege.png',
	priority = 118,
},
[120] ={
	id = 120,
	btn = 'StarWarMbai',
	name = '@act206Hud1',
	icon = 'HUD_StarWars_Worship.png',
	priority = 1,
},
[121] ={
	id = 121,
	btn = 'ViewDetailXZQ',
	name = '@ViewDetail',
	icon = 'HUD_Explain.png',
	priority = 121,
},
[122] ={
	id = 122,
	btn = 'SignUpXZQ',
	name = '@SignUp',
	icon = 'HUD_SignUp.png',
	priority = 122,
},
[123] ={
	id = 123,
	btn = 'AttackXZQ',
	name = '@DoAttack',
	icon = 'HUD_Attack.png',
	priority = 123,
},
[124] ={
	id = 124,
	btn = 'SpyXZQ',
	name = '@Spy',
	icon = 'HUD_Spy.png',
	priority = 124,
},
[125] ={
	id = 125,
	btn = 'DeclareWarXZQ',
	name = '@DeclareWar',
	icon = 'HUD_Gather.png',
	priority = 125,
},
[126] ={
	id = 126,
	btn = 'MassReinforceXZQ',
	name = '@MassReinforce',
	icon = 'HUD_GatherWorldHelp.png',
	priority = 126,
},
[127] ={
	id = 127,
	btn = 'ReinforceXZQ',
	name = '@Reinforce',
	icon = 'HUD_WorldHelp.png',
	priority = 127,
},
[128] ={
	id = 128,
	btn = 'RecallXZQ',
	name = '@Recall',
	icon = 'HUD_MarchRecall.png',
	priority = 128,
},
[129] ={
	id = 129,
	btn = 'ArmyDetailXZQ',
	name = '@TroopsInfo',
	icon = 'HUD_ArmyDetails.png',
	priority = 129,
},
[130] ={
	id = 130,
	btn = 'CancelSignUpXZQ',
	name = '@CancelSignUp',
	icon = 'HUD_SignUp.png',
	priority = 130,
},
[131] ={
	id = 131,
	btn = 'AbandonXZQ',
	name = '@AbandonXZQ',
	icon = 'HUD_Abandon.png',
	priority = 131,
},
[145] ={
	id = 145,
	btn = 'SpeedMarch',
	name = '@CyborgText44',
	icon = 'HUD_WorldHelp.png',
	priority = 56,
},
[193] ={
	id = 193,
	btn = 'AutoTaraLabs',
	name = '@AutoTaraLabs',
	icon = 'HUD_TagOn.png',
	priority = 93,
},
[146] ={
	id = 146,
	btn = 'Destory',
	name = '@DYZZDestory',
	icon = 'HUD_5v5_Destroy.png',
	priority = 94,
},
[132] ={
	id = 132,
	btn = 'BuildingDetailNS',
	name = '@BuildingDetailNS',
	icon = 'HUD_Explain.png',
	priority = 132,
},
[133] ={
	id = 133,
	btn = 'ReBuildingNS',
	name = '@ReBuildingNS',
	icon = 'HUD_BuildRebuild.png',
	priority = 133,
},
[134] ={
	id = 134,
	btn = 'BuildingUpgradeNS',
	name = '@BuildingUpgradeNS',
	icon = 'HUD_BuildUpgrade.png',
	priority = 134,
},
[135] ={
	id = 135,
	btn = 'ReBuildingResNS',
	name = '@ReBuildingResNS',
	icon = 'HUD_Donate.png',
	priority = 135,
},
[136] ={
	id = 136,
	btn = 'BuildingConstructionNS',
	name = '@BuildingConstructionNS',
	icon = 'HUD_Build.png',
	priority = 136,
},
[137] ={
	id = 137,
	btn = 'EntrustNS',
	name = '@EntrustNS',
	icon = 'HUD_NationTask.png',
	priority = 137,
},
[138] ={
	id = 138,
	btn = 'TechnologyNS',
	name = '@TechnologyNS',
	icon = 'HUD_NationTech.png',
	priority = 138,
},
[139] ={
	id = 139,
	btn = 'SpaceshipNS',
	name = '@SpaceshipNS',
	icon = 'HUD_NationAviation_Reform.png',
	priority = 139,
},
[140] ={
	id = 140,
	btn = 'TreasuryNS',
	name = '@TreasuryNS',
	icon = 'HUD_NationWarehouse.png',
	priority = 140,
},
[141] ={
	id = 141,
	btn = 'HospitalNS',
	name = '@HospitalNS',
	icon = 'HUD_NationHeal.png',
	priority = 141,
},
[142] ={
	id = 142,
	btn = 'UniverseNS',
	name = '@UniverseNS',
	icon = 'HUD_NationAviation.png',
	priority = 142,
},
[143] ={
	id = 143,
	btn = 'ReBuildingFundNS',
	name = '@ReBuildingFundNS',
	icon = 'HUD_BuildDonate.png',
	priority = 143,
},
[147] ={
	id = 147,
	btn = 'ChestGet',
	name = '@CrossLang51',
	icon = 'HUD_CrossServer_Cliam.png',
	priority = 95,
},
[148] ={
	id = 148,
	btn = 'HOFInfo',
	name = '@HOFLang1',
	icon = 'HUD_Tiberium_HoF.png',
	priority = 145,
},
[149] ={
	id = 149,
	btn = 'YQZZDeclareWar',
	name = '@YQZZLang20',
	icon = 'HUD_YQZZ_02.png',
	priority = 57,
},
[150] ={
	id = 150,
	btn = 'SPBoxCollection',
	name = '@spaceMechaHud1',
	icon = 'HUD_Collect.png',
	priority = 34,
},
[151] ={
	id = 151,
	btn = 'YQZZShotBuild',
	name = '@yqzzSkillName1',
	icon = 'HUD_LaunchNuclear.png',
	priority = 34,
},
[152] ={
	id = 152,
	btn = 'YQZZKuaiJijie',
	name = '@yqzzSkillName2',
	icon = 'HUD_WorldHelp.png',
	priority = 34,
},
[153] ={
	id = 153,
	btn = 'YQZZYanZhen',
	name = '@yqzzSkillName3',
	icon = 'HUD_YQZZ_04.png',
	priority = 34,
},
[154] ={
	id = 154,
	btn = 'YQZZLijihuifu',
	name = '@yqzzSkillName4',
	icon = 'HUD_YQZZ_03.png',
	priority = 34,
},
[155] ={
	id = 155,
	btn = 'TiberiumControl',
	name = '@TiberiumControl',
	icon = 'HUD_WorldWar_Diplomacy.png',
	priority = 34,
},
[156] ={
	id = 156,
	btn = 'ShareCoord',
	name = '@ShareCoord',
	icon = 'HUD_MoveCity.png',
	priority = 146,
},
[157] ={
	id = 157,
	btn = 'CollectCoord',
	name = '@CollectCoord',
	icon = 'HUD_MoveCity.png',
	priority = 147,
},
[158] ={
	id = 158,
	btn = 'AllianceBossOpen',
	name = '@AllianceBossOpen',
	icon = 'HUD_SignUp.png',
	priority = 148,
},
[159] ={
	id = 159,
	btn = 'AllianceBossRewardShow',
	name = '@AllianceBossRewardShow',
	icon = 'HUD_TESStrUnlock.png',
	priority = 149,
},
[160] ={
	id = 160,
	btn = 'AllianceBossDestroy',
	name = '@AllianceBossDestroy',
	icon = 'HUD_RemoveResource.png',
	priority = 150,
},
[161] ={
	id = 161,
	btn = 'FoggySingleAttack',
	name = '@RAFoggySingleAttackButton',
	icon = 'HUD_Attack.png',
	priority = 999,
}
}
return world_HUD_conf
